// Code generated by go-swagger; DO NOT EDIT.

package team_create

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/janberktold/go-roblox/develop/models"
)

// DELETEV1UniversesUniverseIDTeamcreateMembershipsReader is a Reader for the DELETEV1UniversesUniverseIDTeamcreateMemberships structure.
type DELETEV1UniversesUniverseIDTeamcreateMembershipsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DELETEV1UniversesUniverseIDTeamcreateMembershipsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewDELETEV1UniversesUniverseIDTeamcreateMembershipsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewDELETEV1UniversesUniverseIDTeamcreateMembershipsBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 401:
		result := NewDELETEV1UniversesUniverseIDTeamcreateMembershipsUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 403:
		result := NewDELETEV1UniversesUniverseIDTeamcreateMembershipsForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewDELETEV1UniversesUniverseIDTeamcreateMembershipsOK creates a DELETEV1UniversesUniverseIDTeamcreateMembershipsOK with default headers values
func NewDELETEV1UniversesUniverseIDTeamcreateMembershipsOK() *DELETEV1UniversesUniverseIDTeamcreateMembershipsOK {
	return &DELETEV1UniversesUniverseIDTeamcreateMembershipsOK{}
}

/*DELETEV1UniversesUniverseIDTeamcreateMembershipsOK handles this case with default header values.

DELETEV1UniversesUniverseIDTeamcreateMembershipsOK d e l e t e v1 universes universe Id teamcreate memberships o k
*/
type DELETEV1UniversesUniverseIDTeamcreateMembershipsOK struct {
	Payload models.APIEmptyResponseModel
}

func (o *DELETEV1UniversesUniverseIDTeamcreateMembershipsOK) Error() string {
	return fmt.Sprintf("[DELETE /v1/universes/{universeId}/teamcreate/memberships][%d] dELETEV1UniversesUniverseIdTeamcreateMembershipsOK  %+v", 200, o.Payload)
}

func (o *DELETEV1UniversesUniverseIDTeamcreateMembershipsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDELETEV1UniversesUniverseIDTeamcreateMembershipsBadRequest creates a DELETEV1UniversesUniverseIDTeamcreateMembershipsBadRequest with default headers values
func NewDELETEV1UniversesUniverseIDTeamcreateMembershipsBadRequest() *DELETEV1UniversesUniverseIDTeamcreateMembershipsBadRequest {
	return &DELETEV1UniversesUniverseIDTeamcreateMembershipsBadRequest{}
}

/*DELETEV1UniversesUniverseIDTeamcreateMembershipsBadRequest handles this case with default header values.

{Roblox.Api.Develop.ResponseEnums.TeamCreateErrors.InvalidUniverse} OR {Roblox.Api.Develop.ResponseEnums.TeamCreateErrors.InvalidUser}
*/
type DELETEV1UniversesUniverseIDTeamcreateMembershipsBadRequest struct {
}

func (o *DELETEV1UniversesUniverseIDTeamcreateMembershipsBadRequest) Error() string {
	return fmt.Sprintf("[DELETE /v1/universes/{universeId}/teamcreate/memberships][%d] dELETEV1UniversesUniverseIdTeamcreateMembershipsBadRequest ", 400)
}

func (o *DELETEV1UniversesUniverseIDTeamcreateMembershipsBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDELETEV1UniversesUniverseIDTeamcreateMembershipsUnauthorized creates a DELETEV1UniversesUniverseIDTeamcreateMembershipsUnauthorized with default headers values
func NewDELETEV1UniversesUniverseIDTeamcreateMembershipsUnauthorized() *DELETEV1UniversesUniverseIDTeamcreateMembershipsUnauthorized {
	return &DELETEV1UniversesUniverseIDTeamcreateMembershipsUnauthorized{}
}

/*DELETEV1UniversesUniverseIDTeamcreateMembershipsUnauthorized handles this case with default header values.

{Roblox.Api.Develop.ResponseEnums.TeamCreateErrors.Unauthorized}
*/
type DELETEV1UniversesUniverseIDTeamcreateMembershipsUnauthorized struct {
}

func (o *DELETEV1UniversesUniverseIDTeamcreateMembershipsUnauthorized) Error() string {
	return fmt.Sprintf("[DELETE /v1/universes/{universeId}/teamcreate/memberships][%d] dELETEV1UniversesUniverseIdTeamcreateMembershipsUnauthorized ", 401)
}

func (o *DELETEV1UniversesUniverseIDTeamcreateMembershipsUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDELETEV1UniversesUniverseIDTeamcreateMembershipsForbidden creates a DELETEV1UniversesUniverseIDTeamcreateMembershipsForbidden with default headers values
func NewDELETEV1UniversesUniverseIDTeamcreateMembershipsForbidden() *DELETEV1UniversesUniverseIDTeamcreateMembershipsForbidden {
	return &DELETEV1UniversesUniverseIDTeamcreateMembershipsForbidden{}
}

/*DELETEV1UniversesUniverseIDTeamcreateMembershipsForbidden handles this case with default header values.

{Roblox.Api.Develop.ResponseEnums.TeamCreateErrors.TeamCreateDisabled}
*/
type DELETEV1UniversesUniverseIDTeamcreateMembershipsForbidden struct {
}

func (o *DELETEV1UniversesUniverseIDTeamcreateMembershipsForbidden) Error() string {
	return fmt.Sprintf("[DELETE /v1/universes/{universeId}/teamcreate/memberships][%d] dELETEV1UniversesUniverseIdTeamcreateMembershipsForbidden ", 403)
}

func (o *DELETEV1UniversesUniverseIDTeamcreateMembershipsForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
