// Code generated by go-swagger; DO NOT EDIT.

package team_create

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/janberktold/go-roblox/develop/models"
)

// NewDELETEV1UniversesUniverseIDTeamcreateMembershipsParams creates a new DELETEV1UniversesUniverseIDTeamcreateMembershipsParams object
// with the default values initialized.
func NewDELETEV1UniversesUniverseIDTeamcreateMembershipsParams() *DELETEV1UniversesUniverseIDTeamcreateMembershipsParams {
	var ()
	return &DELETEV1UniversesUniverseIDTeamcreateMembershipsParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDELETEV1UniversesUniverseIDTeamcreateMembershipsParamsWithTimeout creates a new DELETEV1UniversesUniverseIDTeamcreateMembershipsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDELETEV1UniversesUniverseIDTeamcreateMembershipsParamsWithTimeout(timeout time.Duration) *DELETEV1UniversesUniverseIDTeamcreateMembershipsParams {
	var ()
	return &DELETEV1UniversesUniverseIDTeamcreateMembershipsParams{

		timeout: timeout,
	}
}

// NewDELETEV1UniversesUniverseIDTeamcreateMembershipsParamsWithContext creates a new DELETEV1UniversesUniverseIDTeamcreateMembershipsParams object
// with the default values initialized, and the ability to set a context for a request
func NewDELETEV1UniversesUniverseIDTeamcreateMembershipsParamsWithContext(ctx context.Context) *DELETEV1UniversesUniverseIDTeamcreateMembershipsParams {
	var ()
	return &DELETEV1UniversesUniverseIDTeamcreateMembershipsParams{

		Context: ctx,
	}
}

// NewDELETEV1UniversesUniverseIDTeamcreateMembershipsParamsWithHTTPClient creates a new DELETEV1UniversesUniverseIDTeamcreateMembershipsParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDELETEV1UniversesUniverseIDTeamcreateMembershipsParamsWithHTTPClient(client *http.Client) *DELETEV1UniversesUniverseIDTeamcreateMembershipsParams {
	var ()
	return &DELETEV1UniversesUniverseIDTeamcreateMembershipsParams{
		HTTPClient: client,
	}
}

/*DELETEV1UniversesUniverseIDTeamcreateMembershipsParams contains all the parameters to send to the API endpoint
for the d e l e t e v1 universes universe Id teamcreate memberships operation typically these are written to a http.Request
*/
type DELETEV1UniversesUniverseIDTeamcreateMembershipsParams struct {

	/*Request
	  The request body.

	*/
	Request *models.TeamCreateMembershipRequest
	/*UniverseID
	  The universe Id.

	*/
	UniverseID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the d e l e t e v1 universes universe Id teamcreate memberships params
func (o *DELETEV1UniversesUniverseIDTeamcreateMembershipsParams) WithTimeout(timeout time.Duration) *DELETEV1UniversesUniverseIDTeamcreateMembershipsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the d e l e t e v1 universes universe Id teamcreate memberships params
func (o *DELETEV1UniversesUniverseIDTeamcreateMembershipsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the d e l e t e v1 universes universe Id teamcreate memberships params
func (o *DELETEV1UniversesUniverseIDTeamcreateMembershipsParams) WithContext(ctx context.Context) *DELETEV1UniversesUniverseIDTeamcreateMembershipsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the d e l e t e v1 universes universe Id teamcreate memberships params
func (o *DELETEV1UniversesUniverseIDTeamcreateMembershipsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the d e l e t e v1 universes universe Id teamcreate memberships params
func (o *DELETEV1UniversesUniverseIDTeamcreateMembershipsParams) WithHTTPClient(client *http.Client) *DELETEV1UniversesUniverseIDTeamcreateMembershipsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the d e l e t e v1 universes universe Id teamcreate memberships params
func (o *DELETEV1UniversesUniverseIDTeamcreateMembershipsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithRequest adds the request to the d e l e t e v1 universes universe Id teamcreate memberships params
func (o *DELETEV1UniversesUniverseIDTeamcreateMembershipsParams) WithRequest(request *models.TeamCreateMembershipRequest) *DELETEV1UniversesUniverseIDTeamcreateMembershipsParams {
	o.SetRequest(request)
	return o
}

// SetRequest adds the request to the d e l e t e v1 universes universe Id teamcreate memberships params
func (o *DELETEV1UniversesUniverseIDTeamcreateMembershipsParams) SetRequest(request *models.TeamCreateMembershipRequest) {
	o.Request = request
}

// WithUniverseID adds the universeID to the d e l e t e v1 universes universe Id teamcreate memberships params
func (o *DELETEV1UniversesUniverseIDTeamcreateMembershipsParams) WithUniverseID(universeID int64) *DELETEV1UniversesUniverseIDTeamcreateMembershipsParams {
	o.SetUniverseID(universeID)
	return o
}

// SetUniverseID adds the universeId to the d e l e t e v1 universes universe Id teamcreate memberships params
func (o *DELETEV1UniversesUniverseIDTeamcreateMembershipsParams) SetUniverseID(universeID int64) {
	o.UniverseID = universeID
}

// WriteToRequest writes these params to a swagger request
func (o *DELETEV1UniversesUniverseIDTeamcreateMembershipsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Request != nil {
		if err := r.SetBodyParam(o.Request); err != nil {
			return err
		}
	}

	// path param universeId
	if err := r.SetPathParam("universeId", swag.FormatInt64(o.UniverseID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
