// Code generated by go-swagger; DO NOT EDIT.

package team_create

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/janberktold/go-roblox/develop/models"
)

// GETV1UniversesUniverseIDTeamcreateMembershipsReader is a Reader for the GETV1UniversesUniverseIDTeamcreateMemberships structure.
type GETV1UniversesUniverseIDTeamcreateMembershipsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GETV1UniversesUniverseIDTeamcreateMembershipsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGETV1UniversesUniverseIDTeamcreateMembershipsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewGETV1UniversesUniverseIDTeamcreateMembershipsBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 401:
		result := NewGETV1UniversesUniverseIDTeamcreateMembershipsUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 403:
		result := NewGETV1UniversesUniverseIDTeamcreateMembershipsForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGETV1UniversesUniverseIDTeamcreateMembershipsOK creates a GETV1UniversesUniverseIDTeamcreateMembershipsOK with default headers values
func NewGETV1UniversesUniverseIDTeamcreateMembershipsOK() *GETV1UniversesUniverseIDTeamcreateMembershipsOK {
	return &GETV1UniversesUniverseIDTeamcreateMembershipsOK{}
}

/*GETV1UniversesUniverseIDTeamcreateMembershipsOK handles this case with default header values.

GETV1UniversesUniverseIDTeamcreateMembershipsOK g e t v1 universes universe Id teamcreate memberships o k
*/
type GETV1UniversesUniverseIDTeamcreateMembershipsOK struct {
	Payload *models.APIPageResponseUserResponse
}

func (o *GETV1UniversesUniverseIDTeamcreateMembershipsOK) Error() string {
	return fmt.Sprintf("[GET /v1/universes/{universeId}/teamcreate/memberships][%d] gETV1UniversesUniverseIdTeamcreateMembershipsOK  %+v", 200, o.Payload)
}

func (o *GETV1UniversesUniverseIDTeamcreateMembershipsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIPageResponseUserResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGETV1UniversesUniverseIDTeamcreateMembershipsBadRequest creates a GETV1UniversesUniverseIDTeamcreateMembershipsBadRequest with default headers values
func NewGETV1UniversesUniverseIDTeamcreateMembershipsBadRequest() *GETV1UniversesUniverseIDTeamcreateMembershipsBadRequest {
	return &GETV1UniversesUniverseIDTeamcreateMembershipsBadRequest{}
}

/*GETV1UniversesUniverseIDTeamcreateMembershipsBadRequest handles this case with default header values.

{Roblox.Api.Develop.ResponseEnums.TeamCreateErrors.InvalidUniverse}
*/
type GETV1UniversesUniverseIDTeamcreateMembershipsBadRequest struct {
}

func (o *GETV1UniversesUniverseIDTeamcreateMembershipsBadRequest) Error() string {
	return fmt.Sprintf("[GET /v1/universes/{universeId}/teamcreate/memberships][%d] gETV1UniversesUniverseIdTeamcreateMembershipsBadRequest ", 400)
}

func (o *GETV1UniversesUniverseIDTeamcreateMembershipsBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGETV1UniversesUniverseIDTeamcreateMembershipsUnauthorized creates a GETV1UniversesUniverseIDTeamcreateMembershipsUnauthorized with default headers values
func NewGETV1UniversesUniverseIDTeamcreateMembershipsUnauthorized() *GETV1UniversesUniverseIDTeamcreateMembershipsUnauthorized {
	return &GETV1UniversesUniverseIDTeamcreateMembershipsUnauthorized{}
}

/*GETV1UniversesUniverseIDTeamcreateMembershipsUnauthorized handles this case with default header values.

{Roblox.Api.Develop.ResponseEnums.TeamCreateErrors.Unauthorized}
*/
type GETV1UniversesUniverseIDTeamcreateMembershipsUnauthorized struct {
}

func (o *GETV1UniversesUniverseIDTeamcreateMembershipsUnauthorized) Error() string {
	return fmt.Sprintf("[GET /v1/universes/{universeId}/teamcreate/memberships][%d] gETV1UniversesUniverseIdTeamcreateMembershipsUnauthorized ", 401)
}

func (o *GETV1UniversesUniverseIDTeamcreateMembershipsUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGETV1UniversesUniverseIDTeamcreateMembershipsForbidden creates a GETV1UniversesUniverseIDTeamcreateMembershipsForbidden with default headers values
func NewGETV1UniversesUniverseIDTeamcreateMembershipsForbidden() *GETV1UniversesUniverseIDTeamcreateMembershipsForbidden {
	return &GETV1UniversesUniverseIDTeamcreateMembershipsForbidden{}
}

/*GETV1UniversesUniverseIDTeamcreateMembershipsForbidden handles this case with default header values.

{Roblox.Api.Develop.ResponseEnums.TeamCreateErrors.TeamCreateDisabled}
*/
type GETV1UniversesUniverseIDTeamcreateMembershipsForbidden struct {
}

func (o *GETV1UniversesUniverseIDTeamcreateMembershipsForbidden) Error() string {
	return fmt.Sprintf("[GET /v1/universes/{universeId}/teamcreate/memberships][%d] gETV1UniversesUniverseIdTeamcreateMembershipsForbidden ", 403)
}

func (o *GETV1UniversesUniverseIDTeamcreateMembershipsForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
