// Code generated by go-swagger; DO NOT EDIT.

package team_create

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGETV1UserTeamcreateMembershipsParams creates a new GETV1UserTeamcreateMembershipsParams object
// with the default values initialized.
func NewGETV1UserTeamcreateMembershipsParams() *GETV1UserTeamcreateMembershipsParams {
	var (
		limitDefault     = int32(10)
		sortOrderDefault = string("Asc")
	)
	return &GETV1UserTeamcreateMembershipsParams{
		Limit:     &limitDefault,
		SortOrder: &sortOrderDefault,

		timeout: cr.DefaultTimeout,
	}
}

// NewGETV1UserTeamcreateMembershipsParamsWithTimeout creates a new GETV1UserTeamcreateMembershipsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGETV1UserTeamcreateMembershipsParamsWithTimeout(timeout time.Duration) *GETV1UserTeamcreateMembershipsParams {
	var (
		limitDefault     = int32(10)
		sortOrderDefault = string("Asc")
	)
	return &GETV1UserTeamcreateMembershipsParams{
		Limit:     &limitDefault,
		SortOrder: &sortOrderDefault,

		timeout: timeout,
	}
}

// NewGETV1UserTeamcreateMembershipsParamsWithContext creates a new GETV1UserTeamcreateMembershipsParams object
// with the default values initialized, and the ability to set a context for a request
func NewGETV1UserTeamcreateMembershipsParamsWithContext(ctx context.Context) *GETV1UserTeamcreateMembershipsParams {
	var (
		limitDefault     = int32(10)
		sortOrderDefault = string("Asc")
	)
	return &GETV1UserTeamcreateMembershipsParams{
		Limit:     &limitDefault,
		SortOrder: &sortOrderDefault,

		Context: ctx,
	}
}

// NewGETV1UserTeamcreateMembershipsParamsWithHTTPClient creates a new GETV1UserTeamcreateMembershipsParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGETV1UserTeamcreateMembershipsParamsWithHTTPClient(client *http.Client) *GETV1UserTeamcreateMembershipsParams {
	var (
		limitDefault     = int32(10)
		sortOrderDefault = string("Asc")
	)
	return &GETV1UserTeamcreateMembershipsParams{
		Limit:      &limitDefault,
		SortOrder:  &sortOrderDefault,
		HTTPClient: client,
	}
}

/*GETV1UserTeamcreateMembershipsParams contains all the parameters to send to the API endpoint
for the g e t v1 user teamcreate memberships operation typically these are written to a http.Request
*/
type GETV1UserTeamcreateMembershipsParams struct {

	/*Cursor
	  The paging cursor for the previous or next page.

	*/
	Cursor *string
	/*Limit
	  The amount of results per request.

	*/
	Limit *int32
	/*SortOrder
	  TeamCreate membership grant date

	*/
	SortOrder *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the g e t v1 user teamcreate memberships params
func (o *GETV1UserTeamcreateMembershipsParams) WithTimeout(timeout time.Duration) *GETV1UserTeamcreateMembershipsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the g e t v1 user teamcreate memberships params
func (o *GETV1UserTeamcreateMembershipsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the g e t v1 user teamcreate memberships params
func (o *GETV1UserTeamcreateMembershipsParams) WithContext(ctx context.Context) *GETV1UserTeamcreateMembershipsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the g e t v1 user teamcreate memberships params
func (o *GETV1UserTeamcreateMembershipsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the g e t v1 user teamcreate memberships params
func (o *GETV1UserTeamcreateMembershipsParams) WithHTTPClient(client *http.Client) *GETV1UserTeamcreateMembershipsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the g e t v1 user teamcreate memberships params
func (o *GETV1UserTeamcreateMembershipsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithCursor adds the cursor to the g e t v1 user teamcreate memberships params
func (o *GETV1UserTeamcreateMembershipsParams) WithCursor(cursor *string) *GETV1UserTeamcreateMembershipsParams {
	o.SetCursor(cursor)
	return o
}

// SetCursor adds the cursor to the g e t v1 user teamcreate memberships params
func (o *GETV1UserTeamcreateMembershipsParams) SetCursor(cursor *string) {
	o.Cursor = cursor
}

// WithLimit adds the limit to the g e t v1 user teamcreate memberships params
func (o *GETV1UserTeamcreateMembershipsParams) WithLimit(limit *int32) *GETV1UserTeamcreateMembershipsParams {
	o.SetLimit(limit)
	return o
}

// SetLimit adds the limit to the g e t v1 user teamcreate memberships params
func (o *GETV1UserTeamcreateMembershipsParams) SetLimit(limit *int32) {
	o.Limit = limit
}

// WithSortOrder adds the sortOrder to the g e t v1 user teamcreate memberships params
func (o *GETV1UserTeamcreateMembershipsParams) WithSortOrder(sortOrder *string) *GETV1UserTeamcreateMembershipsParams {
	o.SetSortOrder(sortOrder)
	return o
}

// SetSortOrder adds the sortOrder to the g e t v1 user teamcreate memberships params
func (o *GETV1UserTeamcreateMembershipsParams) SetSortOrder(sortOrder *string) {
	o.SortOrder = sortOrder
}

// WriteToRequest writes these params to a swagger request
func (o *GETV1UserTeamcreateMembershipsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Cursor != nil {

		// query param cursor
		var qrCursor string
		if o.Cursor != nil {
			qrCursor = *o.Cursor
		}
		qCursor := qrCursor
		if qCursor != "" {
			if err := r.SetQueryParam("cursor", qCursor); err != nil {
				return err
			}
		}

	}

	if o.Limit != nil {

		// query param limit
		var qrLimit int32
		if o.Limit != nil {
			qrLimit = *o.Limit
		}
		qLimit := swag.FormatInt32(qrLimit)
		if qLimit != "" {
			if err := r.SetQueryParam("limit", qLimit); err != nil {
				return err
			}
		}

	}

	if o.SortOrder != nil {

		// query param sortOrder
		var qrSortOrder string
		if o.SortOrder != nil {
			qrSortOrder = *o.SortOrder
		}
		qSortOrder := qrSortOrder
		if qSortOrder != "" {
			if err := r.SetQueryParam("sortOrder", qSortOrder); err != nil {
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
