// Code generated by go-swagger; DO NOT EDIT.

package team_create

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/janberktold/go-roblox/develop/models"
)

// POSTV1UniversesUniverseIDTeamcreateMembershipsReader is a Reader for the POSTV1UniversesUniverseIDTeamcreateMemberships structure.
type POSTV1UniversesUniverseIDTeamcreateMembershipsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *POSTV1UniversesUniverseIDTeamcreateMembershipsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewPOSTV1UniversesUniverseIDTeamcreateMembershipsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewPOSTV1UniversesUniverseIDTeamcreateMembershipsBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 401:
		result := NewPOSTV1UniversesUniverseIDTeamcreateMembershipsUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 403:
		result := NewPOSTV1UniversesUniverseIDTeamcreateMembershipsForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewPOSTV1UniversesUniverseIDTeamcreateMembershipsOK creates a POSTV1UniversesUniverseIDTeamcreateMembershipsOK with default headers values
func NewPOSTV1UniversesUniverseIDTeamcreateMembershipsOK() *POSTV1UniversesUniverseIDTeamcreateMembershipsOK {
	return &POSTV1UniversesUniverseIDTeamcreateMembershipsOK{}
}

/*POSTV1UniversesUniverseIDTeamcreateMembershipsOK handles this case with default header values.

POSTV1UniversesUniverseIDTeamcreateMembershipsOK p o s t v1 universes universe Id teamcreate memberships o k
*/
type POSTV1UniversesUniverseIDTeamcreateMembershipsOK struct {
	Payload models.APIEmptyResponseModel
}

func (o *POSTV1UniversesUniverseIDTeamcreateMembershipsOK) Error() string {
	return fmt.Sprintf("[POST /v1/universes/{universeId}/teamcreate/memberships][%d] pOSTV1UniversesUniverseIdTeamcreateMembershipsOK  %+v", 200, o.Payload)
}

func (o *POSTV1UniversesUniverseIDTeamcreateMembershipsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPOSTV1UniversesUniverseIDTeamcreateMembershipsBadRequest creates a POSTV1UniversesUniverseIDTeamcreateMembershipsBadRequest with default headers values
func NewPOSTV1UniversesUniverseIDTeamcreateMembershipsBadRequest() *POSTV1UniversesUniverseIDTeamcreateMembershipsBadRequest {
	return &POSTV1UniversesUniverseIDTeamcreateMembershipsBadRequest{}
}

/*POSTV1UniversesUniverseIDTeamcreateMembershipsBadRequest handles this case with default header values.

{Roblox.Api.Develop.ResponseEnums.TeamCreateErrors.InvalidUniverse} OR {Roblox.Api.Develop.ResponseEnums.TeamCreateErrors.InvalidUser}
*/
type POSTV1UniversesUniverseIDTeamcreateMembershipsBadRequest struct {
}

func (o *POSTV1UniversesUniverseIDTeamcreateMembershipsBadRequest) Error() string {
	return fmt.Sprintf("[POST /v1/universes/{universeId}/teamcreate/memberships][%d] pOSTV1UniversesUniverseIdTeamcreateMembershipsBadRequest ", 400)
}

func (o *POSTV1UniversesUniverseIDTeamcreateMembershipsBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewPOSTV1UniversesUniverseIDTeamcreateMembershipsUnauthorized creates a POSTV1UniversesUniverseIDTeamcreateMembershipsUnauthorized with default headers values
func NewPOSTV1UniversesUniverseIDTeamcreateMembershipsUnauthorized() *POSTV1UniversesUniverseIDTeamcreateMembershipsUnauthorized {
	return &POSTV1UniversesUniverseIDTeamcreateMembershipsUnauthorized{}
}

/*POSTV1UniversesUniverseIDTeamcreateMembershipsUnauthorized handles this case with default header values.

{Roblox.Api.Develop.ResponseEnums.TeamCreateErrors.Unauthorized}
*/
type POSTV1UniversesUniverseIDTeamcreateMembershipsUnauthorized struct {
}

func (o *POSTV1UniversesUniverseIDTeamcreateMembershipsUnauthorized) Error() string {
	return fmt.Sprintf("[POST /v1/universes/{universeId}/teamcreate/memberships][%d] pOSTV1UniversesUniverseIdTeamcreateMembershipsUnauthorized ", 401)
}

func (o *POSTV1UniversesUniverseIDTeamcreateMembershipsUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewPOSTV1UniversesUniverseIDTeamcreateMembershipsForbidden creates a POSTV1UniversesUniverseIDTeamcreateMembershipsForbidden with default headers values
func NewPOSTV1UniversesUniverseIDTeamcreateMembershipsForbidden() *POSTV1UniversesUniverseIDTeamcreateMembershipsForbidden {
	return &POSTV1UniversesUniverseIDTeamcreateMembershipsForbidden{}
}

/*POSTV1UniversesUniverseIDTeamcreateMembershipsForbidden handles this case with default header values.

{Roblox.Api.Develop.ResponseEnums.TeamCreateErrors.TeamCreateDisabled}
*/
type POSTV1UniversesUniverseIDTeamcreateMembershipsForbidden struct {
}

func (o *POSTV1UniversesUniverseIDTeamcreateMembershipsForbidden) Error() string {
	return fmt.Sprintf("[POST /v1/universes/{universeId}/teamcreate/memberships][%d] pOSTV1UniversesUniverseIdTeamcreateMembershipsForbidden ", 403)
}

func (o *POSTV1UniversesUniverseIDTeamcreateMembershipsForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
