// Code generated by go-swagger; DO NOT EDIT.

package passwords

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/janberktold/go-roblox/auth/models"
)

// NewPOSTV1PasswordsResetSendParams creates a new POSTV1PasswordsResetSendParams object
// with the default values initialized.
func NewPOSTV1PasswordsResetSendParams() *POSTV1PasswordsResetSendParams {
	var ()
	return &POSTV1PasswordsResetSendParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPOSTV1PasswordsResetSendParamsWithTimeout creates a new POSTV1PasswordsResetSendParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPOSTV1PasswordsResetSendParamsWithTimeout(timeout time.Duration) *POSTV1PasswordsResetSendParams {
	var ()
	return &POSTV1PasswordsResetSendParams{

		timeout: timeout,
	}
}

// NewPOSTV1PasswordsResetSendParamsWithContext creates a new POSTV1PasswordsResetSendParams object
// with the default values initialized, and the ability to set a context for a request
func NewPOSTV1PasswordsResetSendParamsWithContext(ctx context.Context) *POSTV1PasswordsResetSendParams {
	var ()
	return &POSTV1PasswordsResetSendParams{

		Context: ctx,
	}
}

// NewPOSTV1PasswordsResetSendParamsWithHTTPClient creates a new POSTV1PasswordsResetSendParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPOSTV1PasswordsResetSendParamsWithHTTPClient(client *http.Client) *POSTV1PasswordsResetSendParams {
	var ()
	return &POSTV1PasswordsResetSendParams{
		HTTPClient: client,
	}
}

/*POSTV1PasswordsResetSendParams contains all the parameters to send to the API endpoint
for the p o s t v1 passwords reset send operation typically these are written to a http.Request
*/
type POSTV1PasswordsResetSendParams struct {

	/*Request
	  The request model containing the username of the user.

	*/
	Request *models.UsernameModel

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the p o s t v1 passwords reset send params
func (o *POSTV1PasswordsResetSendParams) WithTimeout(timeout time.Duration) *POSTV1PasswordsResetSendParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the p o s t v1 passwords reset send params
func (o *POSTV1PasswordsResetSendParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the p o s t v1 passwords reset send params
func (o *POSTV1PasswordsResetSendParams) WithContext(ctx context.Context) *POSTV1PasswordsResetSendParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the p o s t v1 passwords reset send params
func (o *POSTV1PasswordsResetSendParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the p o s t v1 passwords reset send params
func (o *POSTV1PasswordsResetSendParams) WithHTTPClient(client *http.Client) *POSTV1PasswordsResetSendParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the p o s t v1 passwords reset send params
func (o *POSTV1PasswordsResetSendParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithRequest adds the request to the p o s t v1 passwords reset send params
func (o *POSTV1PasswordsResetSendParams) WithRequest(request *models.UsernameModel) *POSTV1PasswordsResetSendParams {
	o.SetRequest(request)
	return o
}

// SetRequest adds the request to the p o s t v1 passwords reset send params
func (o *POSTV1PasswordsResetSendParams) SetRequest(request *models.UsernameModel) {
	o.Request = request
}

// WriteToRequest writes these params to a swagger request
func (o *POSTV1PasswordsResetSendParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Request != nil {
		if err := r.SetBodyParam(o.Request); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
