// Code generated by go-swagger; DO NOT EDIT.

package passwords

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/janberktold/go-roblox/auth/models"
)

// POSTV1PasswordsResetSendReader is a Reader for the POSTV1PasswordsResetSend structure.
type POSTV1PasswordsResetSendReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *POSTV1PasswordsResetSendReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewPOSTV1PasswordsResetSendOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewPOSTV1PasswordsResetSendBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 403:
		result := NewPOSTV1PasswordsResetSendForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 429:
		result := NewPOSTV1PasswordsResetSendTooManyRequests()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewPOSTV1PasswordsResetSendOK creates a POSTV1PasswordsResetSendOK with default headers values
func NewPOSTV1PasswordsResetSendOK() *POSTV1PasswordsResetSendOK {
	return &POSTV1PasswordsResetSendOK{}
}

/*POSTV1PasswordsResetSendOK handles this case with default header values.

The forgot password email successfully sent.
*/
type POSTV1PasswordsResetSendOK struct {
	Payload models.APIEmptyResponseModel
}

func (o *POSTV1PasswordsResetSendOK) Error() string {
	return fmt.Sprintf("[POST /v1/passwords/reset/send][%d] pOSTV1PasswordsResetSendOK  %+v", 200, o.Payload)
}

func (o *POSTV1PasswordsResetSendOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPOSTV1PasswordsResetSendBadRequest creates a POSTV1PasswordsResetSendBadRequest with default headers values
func NewPOSTV1PasswordsResetSendBadRequest() *POSTV1PasswordsResetSendBadRequest {
	return &POSTV1PasswordsResetSendBadRequest{}
}

/*POSTV1PasswordsResetSendBadRequest handles this case with default header values.

{Roblox.Api.Authentication.ResponseEnums.PasswordErrors.InvalidUser}
*/
type POSTV1PasswordsResetSendBadRequest struct {
}

func (o *POSTV1PasswordsResetSendBadRequest) Error() string {
	return fmt.Sprintf("[POST /v1/passwords/reset/send][%d] pOSTV1PasswordsResetSendBadRequest ", 400)
}

func (o *POSTV1PasswordsResetSendBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewPOSTV1PasswordsResetSendForbidden creates a POSTV1PasswordsResetSendForbidden with default headers values
func NewPOSTV1PasswordsResetSendForbidden() *POSTV1PasswordsResetSendForbidden {
	return &POSTV1PasswordsResetSendForbidden{}
}

/*POSTV1PasswordsResetSendForbidden handles this case with default header values.

{Roblox.Api.Authentication.ResponseEnums.PasswordErrors.InvalidAccountStatus}
            OR
            {Roblox.Api.Authentication.ResponseEnums.PasswordErrors.InvalidEmail}
            OR
            {Roblox.Api.Authentication.ResponseEnums.PasswordErrors.FeatureDisabled}
*/
type POSTV1PasswordsResetSendForbidden struct {
}

func (o *POSTV1PasswordsResetSendForbidden) Error() string {
	return fmt.Sprintf("[POST /v1/passwords/reset/send][%d] pOSTV1PasswordsResetSendForbidden ", 403)
}

func (o *POSTV1PasswordsResetSendForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewPOSTV1PasswordsResetSendTooManyRequests creates a POSTV1PasswordsResetSendTooManyRequests with default headers values
func NewPOSTV1PasswordsResetSendTooManyRequests() *POSTV1PasswordsResetSendTooManyRequests {
	return &POSTV1PasswordsResetSendTooManyRequests{}
}

/*POSTV1PasswordsResetSendTooManyRequests handles this case with default header values.

{Roblox.Api.Authentication.ResponseEnums.PasswordErrors.Flooded}
*/
type POSTV1PasswordsResetSendTooManyRequests struct {
}

func (o *POSTV1PasswordsResetSendTooManyRequests) Error() string {
	return fmt.Sprintf("[POST /v1/passwords/reset/send][%d] pOSTV1PasswordsResetSendTooManyRequests ", 429)
}

func (o *POSTV1PasswordsResetSendTooManyRequests) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
