// Code generated by go-swagger; DO NOT EDIT.

package passwords

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/janberktold/go-roblox/auth/models"
)

// NewPOSTV1UserPasswordsChangeParams creates a new POSTV1UserPasswordsChangeParams object
// with the default values initialized.
func NewPOSTV1UserPasswordsChangeParams() *POSTV1UserPasswordsChangeParams {
	var ()
	return &POSTV1UserPasswordsChangeParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPOSTV1UserPasswordsChangeParamsWithTimeout creates a new POSTV1UserPasswordsChangeParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPOSTV1UserPasswordsChangeParamsWithTimeout(timeout time.Duration) *POSTV1UserPasswordsChangeParams {
	var ()
	return &POSTV1UserPasswordsChangeParams{

		timeout: timeout,
	}
}

// NewPOSTV1UserPasswordsChangeParamsWithContext creates a new POSTV1UserPasswordsChangeParams object
// with the default values initialized, and the ability to set a context for a request
func NewPOSTV1UserPasswordsChangeParamsWithContext(ctx context.Context) *POSTV1UserPasswordsChangeParams {
	var ()
	return &POSTV1UserPasswordsChangeParams{

		Context: ctx,
	}
}

// NewPOSTV1UserPasswordsChangeParamsWithHTTPClient creates a new POSTV1UserPasswordsChangeParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPOSTV1UserPasswordsChangeParamsWithHTTPClient(client *http.Client) *POSTV1UserPasswordsChangeParams {
	var ()
	return &POSTV1UserPasswordsChangeParams{
		HTTPClient: client,
	}
}

/*POSTV1UserPasswordsChangeParams contains all the parameters to send to the API endpoint
for the p o s t v1 user passwords change operation typically these are written to a http.Request
*/
type POSTV1UserPasswordsChangeParams struct {

	/*Request
	  The request model including the current password, and the new password.

	*/
	Request *models.PasswordChangeModel

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the p o s t v1 user passwords change params
func (o *POSTV1UserPasswordsChangeParams) WithTimeout(timeout time.Duration) *POSTV1UserPasswordsChangeParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the p o s t v1 user passwords change params
func (o *POSTV1UserPasswordsChangeParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the p o s t v1 user passwords change params
func (o *POSTV1UserPasswordsChangeParams) WithContext(ctx context.Context) *POSTV1UserPasswordsChangeParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the p o s t v1 user passwords change params
func (o *POSTV1UserPasswordsChangeParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the p o s t v1 user passwords change params
func (o *POSTV1UserPasswordsChangeParams) WithHTTPClient(client *http.Client) *POSTV1UserPasswordsChangeParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the p o s t v1 user passwords change params
func (o *POSTV1UserPasswordsChangeParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithRequest adds the request to the p o s t v1 user passwords change params
func (o *POSTV1UserPasswordsChangeParams) WithRequest(request *models.PasswordChangeModel) *POSTV1UserPasswordsChangeParams {
	o.SetRequest(request)
	return o
}

// SetRequest adds the request to the p o s t v1 user passwords change params
func (o *POSTV1UserPasswordsChangeParams) SetRequest(request *models.PasswordChangeModel) {
	o.Request = request
}

// WriteToRequest writes these params to a swagger request
func (o *POSTV1UserPasswordsChangeParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Request != nil {
		if err := r.SetBodyParam(o.Request); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
