// Code generated by go-swagger; DO NOT EDIT.

package social_authentication

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/janberktold/go-roblox/auth/models"
)

// GETV1SocialConnectedProvidersReader is a Reader for the GETV1SocialConnectedProviders structure.
type GETV1SocialConnectedProvidersReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GETV1SocialConnectedProvidersReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGETV1SocialConnectedProvidersOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGETV1SocialConnectedProvidersOK creates a GETV1SocialConnectedProvidersOK with default headers values
func NewGETV1SocialConnectedProvidersOK() *GETV1SocialConnectedProvidersOK {
	return &GETV1SocialConnectedProvidersOK{}
}

/*GETV1SocialConnectedProvidersOK handles this case with default header values.

OK
*/
type GETV1SocialConnectedProvidersOK struct {
	Payload *models.SocialProvidersModel
}

func (o *GETV1SocialConnectedProvidersOK) Error() string {
	return fmt.Sprintf("[GET /v1/social/connected-providers][%d] gETV1SocialConnectedProvidersOK  %+v", 200, o.Payload)
}

func (o *GETV1SocialConnectedProvidersOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.SocialProvidersModel)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
