// Code generated by go-swagger; DO NOT EDIT.

package social_authentication

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/janberktold/go-roblox/auth/models"
)

// POSTV1SocialProviderDisconnectReader is a Reader for the POSTV1SocialProviderDisconnect structure.
type POSTV1SocialProviderDisconnectReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *POSTV1SocialProviderDisconnectReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewPOSTV1SocialProviderDisconnectOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewPOSTV1SocialProviderDisconnectBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 403:
		result := NewPOSTV1SocialProviderDisconnectForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewPOSTV1SocialProviderDisconnectOK creates a POSTV1SocialProviderDisconnectOK with default headers values
func NewPOSTV1SocialProviderDisconnectOK() *POSTV1SocialProviderDisconnectOK {
	return &POSTV1SocialProviderDisconnectOK{}
}

/*POSTV1SocialProviderDisconnectOK handles this case with default header values.

OK
*/
type POSTV1SocialProviderDisconnectOK struct {
	Payload *models.APISuccessResponse
}

func (o *POSTV1SocialProviderDisconnectOK) Error() string {
	return fmt.Sprintf("[POST /v1/social/{provider}/disconnect][%d] pOSTV1SocialProviderDisconnectOK  %+v", 200, o.Payload)
}

func (o *POSTV1SocialProviderDisconnectOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APISuccessResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPOSTV1SocialProviderDisconnectBadRequest creates a POSTV1SocialProviderDisconnectBadRequest with default headers values
func NewPOSTV1SocialProviderDisconnectBadRequest() *POSTV1SocialProviderDisconnectBadRequest {
	return &POSTV1SocialProviderDisconnectBadRequest{}
}

/*POSTV1SocialProviderDisconnectBadRequest handles this case with default header values.

Bad Request
*/
type POSTV1SocialProviderDisconnectBadRequest struct {
}

func (o *POSTV1SocialProviderDisconnectBadRequest) Error() string {
	return fmt.Sprintf("[POST /v1/social/{provider}/disconnect][%d] pOSTV1SocialProviderDisconnectBadRequest ", 400)
}

func (o *POSTV1SocialProviderDisconnectBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewPOSTV1SocialProviderDisconnectForbidden creates a POSTV1SocialProviderDisconnectForbidden with default headers values
func NewPOSTV1SocialProviderDisconnectForbidden() *POSTV1SocialProviderDisconnectForbidden {
	return &POSTV1SocialProviderDisconnectForbidden{}
}

/*POSTV1SocialProviderDisconnectForbidden handles this case with default header values.

Forbidden
*/
type POSTV1SocialProviderDisconnectForbidden struct {
}

func (o *POSTV1SocialProviderDisconnectForbidden) Error() string {
	return fmt.Sprintf("[POST /v1/social/{provider}/disconnect][%d] pOSTV1SocialProviderDisconnectForbidden ", 403)
}

func (o *POSTV1SocialProviderDisconnectForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
