// Code generated by go-swagger; DO NOT EDIT.

package social_authentication

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewPOSTV1SocialProviderDisconnectParams creates a new POSTV1SocialProviderDisconnectParams object
// with the default values initialized.
func NewPOSTV1SocialProviderDisconnectParams() *POSTV1SocialProviderDisconnectParams {
	var ()
	return &POSTV1SocialProviderDisconnectParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPOSTV1SocialProviderDisconnectParamsWithTimeout creates a new POSTV1SocialProviderDisconnectParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPOSTV1SocialProviderDisconnectParamsWithTimeout(timeout time.Duration) *POSTV1SocialProviderDisconnectParams {
	var ()
	return &POSTV1SocialProviderDisconnectParams{

		timeout: timeout,
	}
}

// NewPOSTV1SocialProviderDisconnectParamsWithContext creates a new POSTV1SocialProviderDisconnectParams object
// with the default values initialized, and the ability to set a context for a request
func NewPOSTV1SocialProviderDisconnectParamsWithContext(ctx context.Context) *POSTV1SocialProviderDisconnectParams {
	var ()
	return &POSTV1SocialProviderDisconnectParams{

		Context: ctx,
	}
}

// NewPOSTV1SocialProviderDisconnectParamsWithHTTPClient creates a new POSTV1SocialProviderDisconnectParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPOSTV1SocialProviderDisconnectParamsWithHTTPClient(client *http.Client) *POSTV1SocialProviderDisconnectParams {
	var ()
	return &POSTV1SocialProviderDisconnectParams{
		HTTPClient: client,
	}
}

/*POSTV1SocialProviderDisconnectParams contains all the parameters to send to the API endpoint
for the p o s t v1 social provider disconnect operation typically these are written to a http.Request
*/
type POSTV1SocialProviderDisconnectParams struct {

	/*Provider
	  The social network provider, e.g., Facebook.

	*/
	Provider string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the p o s t v1 social provider disconnect params
func (o *POSTV1SocialProviderDisconnectParams) WithTimeout(timeout time.Duration) *POSTV1SocialProviderDisconnectParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the p o s t v1 social provider disconnect params
func (o *POSTV1SocialProviderDisconnectParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the p o s t v1 social provider disconnect params
func (o *POSTV1SocialProviderDisconnectParams) WithContext(ctx context.Context) *POSTV1SocialProviderDisconnectParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the p o s t v1 social provider disconnect params
func (o *POSTV1SocialProviderDisconnectParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the p o s t v1 social provider disconnect params
func (o *POSTV1SocialProviderDisconnectParams) WithHTTPClient(client *http.Client) *POSTV1SocialProviderDisconnectParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the p o s t v1 social provider disconnect params
func (o *POSTV1SocialProviderDisconnectParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithProvider adds the provider to the p o s t v1 social provider disconnect params
func (o *POSTV1SocialProviderDisconnectParams) WithProvider(provider string) *POSTV1SocialProviderDisconnectParams {
	o.SetProvider(provider)
	return o
}

// SetProvider adds the provider to the p o s t v1 social provider disconnect params
func (o *POSTV1SocialProviderDisconnectParams) SetProvider(provider string) {
	o.Provider = provider
}

// WriteToRequest writes these params to a swagger request
func (o *POSTV1SocialProviderDisconnectParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param provider
	if err := r.SetPathParam("provider", o.Provider); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
