// Code generated by go-swagger; DO NOT EDIT.

package assets

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/janberktold/go-roblox/inventory/models"
)

// GETV1RecommendationsAssetTypeIDReader is a Reader for the GETV1RecommendationsAssetTypeID structure.
type GETV1RecommendationsAssetTypeIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GETV1RecommendationsAssetTypeIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGETV1RecommendationsAssetTypeIDOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGETV1RecommendationsAssetTypeIDOK creates a GETV1RecommendationsAssetTypeIDOK with default headers values
func NewGETV1RecommendationsAssetTypeIDOK() *GETV1RecommendationsAssetTypeIDOK {
	return &GETV1RecommendationsAssetTypeIDOK{}
}

/*GETV1RecommendationsAssetTypeIDOK handles this case with default header values.

OK
*/
type GETV1RecommendationsAssetTypeIDOK struct {
	Payload *models.APILegacyPageResponseRecommendationViewModel
}

func (o *GETV1RecommendationsAssetTypeIDOK) Error() string {
	return fmt.Sprintf("[GET /v1/recommendations/{assetTypeId}][%d] gETV1RecommendationsAssetTypeIdOK  %+v", 200, o.Payload)
}

func (o *GETV1RecommendationsAssetTypeIDOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APILegacyPageResponseRecommendationViewModel)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
