// Code generated by go-swagger; DO NOT EDIT.

package assets

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/janberktold/go-roblox/inventory/models"
)

// GETV1AssetsAssetIDOwnersReader is a Reader for the GETV1AssetsAssetIDOwners structure.
type GETV1AssetsAssetIDOwnersReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GETV1AssetsAssetIDOwnersReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGETV1AssetsAssetIDOwnersOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewGETV1AssetsAssetIDOwnersBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGETV1AssetsAssetIDOwnersOK creates a GETV1AssetsAssetIDOwnersOK with default headers values
func NewGETV1AssetsAssetIDOwnersOK() *GETV1AssetsAssetIDOwnersOK {
	return &GETV1AssetsAssetIDOwnersOK{}
}

/*GETV1AssetsAssetIDOwnersOK handles this case with default header values.

GETV1AssetsAssetIDOwnersOK g e t v1 assets asset Id owners o k
*/
type GETV1AssetsAssetIDOwnersOK struct {
	Payload *models.APIPageResponseUserAssetModel
}

func (o *GETV1AssetsAssetIDOwnersOK) Error() string {
	return fmt.Sprintf("[GET /v1/assets/{assetId}/owners][%d] gETV1AssetsAssetIdOwnersOK  %+v", 200, o.Payload)
}

func (o *GETV1AssetsAssetIDOwnersOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIPageResponseUserAssetModel)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGETV1AssetsAssetIDOwnersBadRequest creates a GETV1AssetsAssetIDOwnersBadRequest with default headers values
func NewGETV1AssetsAssetIDOwnersBadRequest() *GETV1AssetsAssetIDOwnersBadRequest {
	return &GETV1AssetsAssetIDOwnersBadRequest{}
}

/*GETV1AssetsAssetIDOwnersBadRequest handles this case with default header values.

Invalid asset id.
*/
type GETV1AssetsAssetIDOwnersBadRequest struct {
}

func (o *GETV1AssetsAssetIDOwnersBadRequest) Error() string {
	return fmt.Sprintf("[GET /v1/assets/{assetId}/owners][%d] gETV1AssetsAssetIdOwnersBadRequest ", 400)
}

func (o *GETV1AssetsAssetIDOwnersBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
