// Code generated by go-swagger; DO NOT EDIT.

package assets

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGETV1RecommendationsAssetTypeIDParams creates a new GETV1RecommendationsAssetTypeIDParams object
// with the default values initialized.
func NewGETV1RecommendationsAssetTypeIDParams() *GETV1RecommendationsAssetTypeIDParams {
	var ()
	return &GETV1RecommendationsAssetTypeIDParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGETV1RecommendationsAssetTypeIDParamsWithTimeout creates a new GETV1RecommendationsAssetTypeIDParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGETV1RecommendationsAssetTypeIDParamsWithTimeout(timeout time.Duration) *GETV1RecommendationsAssetTypeIDParams {
	var ()
	return &GETV1RecommendationsAssetTypeIDParams{

		timeout: timeout,
	}
}

// NewGETV1RecommendationsAssetTypeIDParamsWithContext creates a new GETV1RecommendationsAssetTypeIDParams object
// with the default values initialized, and the ability to set a context for a request
func NewGETV1RecommendationsAssetTypeIDParamsWithContext(ctx context.Context) *GETV1RecommendationsAssetTypeIDParams {
	var ()
	return &GETV1RecommendationsAssetTypeIDParams{

		Context: ctx,
	}
}

// NewGETV1RecommendationsAssetTypeIDParamsWithHTTPClient creates a new GETV1RecommendationsAssetTypeIDParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGETV1RecommendationsAssetTypeIDParamsWithHTTPClient(client *http.Client) *GETV1RecommendationsAssetTypeIDParams {
	var ()
	return &GETV1RecommendationsAssetTypeIDParams{
		HTTPClient: client,
	}
}

/*GETV1RecommendationsAssetTypeIDParams contains all the parameters to send to the API endpoint
for the g e t v1 recommendations asset type Id operation typically these are written to a http.Request
*/
type GETV1RecommendationsAssetTypeIDParams struct {

	/*AssetTypeID
	  The asset type id

	*/
	AssetTypeID int32
	/*ContextAssetID*/
	ContextAssetID *int64
	/*NumItems
	  The number of recommended items to return.

	*/
	NumItems *int32
	/*ThumbHeight*/
	ThumbHeight *int32
	/*ThumbWidth*/
	ThumbWidth *int32

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the g e t v1 recommendations asset type Id params
func (o *GETV1RecommendationsAssetTypeIDParams) WithTimeout(timeout time.Duration) *GETV1RecommendationsAssetTypeIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the g e t v1 recommendations asset type Id params
func (o *GETV1RecommendationsAssetTypeIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the g e t v1 recommendations asset type Id params
func (o *GETV1RecommendationsAssetTypeIDParams) WithContext(ctx context.Context) *GETV1RecommendationsAssetTypeIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the g e t v1 recommendations asset type Id params
func (o *GETV1RecommendationsAssetTypeIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the g e t v1 recommendations asset type Id params
func (o *GETV1RecommendationsAssetTypeIDParams) WithHTTPClient(client *http.Client) *GETV1RecommendationsAssetTypeIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the g e t v1 recommendations asset type Id params
func (o *GETV1RecommendationsAssetTypeIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAssetTypeID adds the assetTypeID to the g e t v1 recommendations asset type Id params
func (o *GETV1RecommendationsAssetTypeIDParams) WithAssetTypeID(assetTypeID int32) *GETV1RecommendationsAssetTypeIDParams {
	o.SetAssetTypeID(assetTypeID)
	return o
}

// SetAssetTypeID adds the assetTypeId to the g e t v1 recommendations asset type Id params
func (o *GETV1RecommendationsAssetTypeIDParams) SetAssetTypeID(assetTypeID int32) {
	o.AssetTypeID = assetTypeID
}

// WithContextAssetID adds the contextAssetID to the g e t v1 recommendations asset type Id params
func (o *GETV1RecommendationsAssetTypeIDParams) WithContextAssetID(contextAssetID *int64) *GETV1RecommendationsAssetTypeIDParams {
	o.SetContextAssetID(contextAssetID)
	return o
}

// SetContextAssetID adds the contextAssetId to the g e t v1 recommendations asset type Id params
func (o *GETV1RecommendationsAssetTypeIDParams) SetContextAssetID(contextAssetID *int64) {
	o.ContextAssetID = contextAssetID
}

// WithNumItems adds the numItems to the g e t v1 recommendations asset type Id params
func (o *GETV1RecommendationsAssetTypeIDParams) WithNumItems(numItems *int32) *GETV1RecommendationsAssetTypeIDParams {
	o.SetNumItems(numItems)
	return o
}

// SetNumItems adds the numItems to the g e t v1 recommendations asset type Id params
func (o *GETV1RecommendationsAssetTypeIDParams) SetNumItems(numItems *int32) {
	o.NumItems = numItems
}

// WithThumbHeight adds the thumbHeight to the g e t v1 recommendations asset type Id params
func (o *GETV1RecommendationsAssetTypeIDParams) WithThumbHeight(thumbHeight *int32) *GETV1RecommendationsAssetTypeIDParams {
	o.SetThumbHeight(thumbHeight)
	return o
}

// SetThumbHeight adds the thumbHeight to the g e t v1 recommendations asset type Id params
func (o *GETV1RecommendationsAssetTypeIDParams) SetThumbHeight(thumbHeight *int32) {
	o.ThumbHeight = thumbHeight
}

// WithThumbWidth adds the thumbWidth to the g e t v1 recommendations asset type Id params
func (o *GETV1RecommendationsAssetTypeIDParams) WithThumbWidth(thumbWidth *int32) *GETV1RecommendationsAssetTypeIDParams {
	o.SetThumbWidth(thumbWidth)
	return o
}

// SetThumbWidth adds the thumbWidth to the g e t v1 recommendations asset type Id params
func (o *GETV1RecommendationsAssetTypeIDParams) SetThumbWidth(thumbWidth *int32) {
	o.ThumbWidth = thumbWidth
}

// WriteToRequest writes these params to a swagger request
func (o *GETV1RecommendationsAssetTypeIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param assetTypeId
	if err := r.SetPathParam("assetTypeId", swag.FormatInt32(o.AssetTypeID)); err != nil {
		return err
	}

	if o.ContextAssetID != nil {

		// query param contextAssetId
		var qrContextAssetID int64
		if o.ContextAssetID != nil {
			qrContextAssetID = *o.ContextAssetID
		}
		qContextAssetID := swag.FormatInt64(qrContextAssetID)
		if qContextAssetID != "" {
			if err := r.SetQueryParam("contextAssetId", qContextAssetID); err != nil {
				return err
			}
		}

	}

	if o.NumItems != nil {

		// query param numItems
		var qrNumItems int32
		if o.NumItems != nil {
			qrNumItems = *o.NumItems
		}
		qNumItems := swag.FormatInt32(qrNumItems)
		if qNumItems != "" {
			if err := r.SetQueryParam("numItems", qNumItems); err != nil {
				return err
			}
		}

	}

	if o.ThumbHeight != nil {

		// query param thumbHeight
		var qrThumbHeight int32
		if o.ThumbHeight != nil {
			qrThumbHeight = *o.ThumbHeight
		}
		qThumbHeight := swag.FormatInt32(qrThumbHeight)
		if qThumbHeight != "" {
			if err := r.SetQueryParam("thumbHeight", qThumbHeight); err != nil {
				return err
			}
		}

	}

	if o.ThumbWidth != nil {

		// query param thumbWidth
		var qrThumbWidth int32
		if o.ThumbWidth != nil {
			qrThumbWidth = *o.ThumbWidth
		}
		qThumbWidth := swag.FormatInt32(qrThumbWidth)
		if qThumbWidth != "" {
			if err := r.SetQueryParam("thumbWidth", qThumbWidth); err != nil {
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
