// Code generated by go-swagger; DO NOT EDIT.

package assets

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGETV1PackagesPackageIDAssetsParams creates a new GETV1PackagesPackageIDAssetsParams object
// with the default values initialized.
func NewGETV1PackagesPackageIDAssetsParams() *GETV1PackagesPackageIDAssetsParams {
	var ()
	return &GETV1PackagesPackageIDAssetsParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGETV1PackagesPackageIDAssetsParamsWithTimeout creates a new GETV1PackagesPackageIDAssetsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGETV1PackagesPackageIDAssetsParamsWithTimeout(timeout time.Duration) *GETV1PackagesPackageIDAssetsParams {
	var ()
	return &GETV1PackagesPackageIDAssetsParams{

		timeout: timeout,
	}
}

// NewGETV1PackagesPackageIDAssetsParamsWithContext creates a new GETV1PackagesPackageIDAssetsParams object
// with the default values initialized, and the ability to set a context for a request
func NewGETV1PackagesPackageIDAssetsParamsWithContext(ctx context.Context) *GETV1PackagesPackageIDAssetsParams {
	var ()
	return &GETV1PackagesPackageIDAssetsParams{

		Context: ctx,
	}
}

// NewGETV1PackagesPackageIDAssetsParamsWithHTTPClient creates a new GETV1PackagesPackageIDAssetsParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGETV1PackagesPackageIDAssetsParamsWithHTTPClient(client *http.Client) *GETV1PackagesPackageIDAssetsParams {
	var ()
	return &GETV1PackagesPackageIDAssetsParams{
		HTTPClient: client,
	}
}

/*GETV1PackagesPackageIDAssetsParams contains all the parameters to send to the API endpoint
for the g e t v1 packages package Id assets operation typically these are written to a http.Request
*/
type GETV1PackagesPackageIDAssetsParams struct {

	/*PackageID
	  The asset ID of the package

	*/
	PackageID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the g e t v1 packages package Id assets params
func (o *GETV1PackagesPackageIDAssetsParams) WithTimeout(timeout time.Duration) *GETV1PackagesPackageIDAssetsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the g e t v1 packages package Id assets params
func (o *GETV1PackagesPackageIDAssetsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the g e t v1 packages package Id assets params
func (o *GETV1PackagesPackageIDAssetsParams) WithContext(ctx context.Context) *GETV1PackagesPackageIDAssetsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the g e t v1 packages package Id assets params
func (o *GETV1PackagesPackageIDAssetsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the g e t v1 packages package Id assets params
func (o *GETV1PackagesPackageIDAssetsParams) WithHTTPClient(client *http.Client) *GETV1PackagesPackageIDAssetsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the g e t v1 packages package Id assets params
func (o *GETV1PackagesPackageIDAssetsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithPackageID adds the packageID to the g e t v1 packages package Id assets params
func (o *GETV1PackagesPackageIDAssetsParams) WithPackageID(packageID int64) *GETV1PackagesPackageIDAssetsParams {
	o.SetPackageID(packageID)
	return o
}

// SetPackageID adds the packageId to the g e t v1 packages package Id assets params
func (o *GETV1PackagesPackageIDAssetsParams) SetPackageID(packageID int64) {
	o.PackageID = packageID
}

// WriteToRequest writes these params to a swagger request
func (o *GETV1PackagesPackageIDAssetsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param packageID
	if err := r.SetPathParam("packageID", swag.FormatInt64(o.PackageID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
