// Code generated by go-swagger; DO NOT EDIT.

package places

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/janberktold/go-roblox/develop/models"
)

// POSTV1PlacesPlaceIDReader is a Reader for the POSTV1PlacesPlaceID structure.
type POSTV1PlacesPlaceIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *POSTV1PlacesPlaceIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewPOSTV1PlacesPlaceIDOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewPOSTV1PlacesPlaceIDBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 401:
		result := NewPOSTV1PlacesPlaceIDUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewPOSTV1PlacesPlaceIDOK creates a POSTV1PlacesPlaceIDOK with default headers values
func NewPOSTV1PlacesPlaceIDOK() *POSTV1PlacesPlaceIDOK {
	return &POSTV1PlacesPlaceIDOK{}
}

/*POSTV1PlacesPlaceIDOK handles this case with default header values.

POSTV1PlacesPlaceIDOK p o s t v1 places place Id o k
*/
type POSTV1PlacesPlaceIDOK struct {
	Payload *models.PlaceModel
}

func (o *POSTV1PlacesPlaceIDOK) Error() string {
	return fmt.Sprintf("[POST /v1/places/{placeId}][%d] pOSTV1PlacesPlaceIdOK  %+v", 200, o.Payload)
}

func (o *POSTV1PlacesPlaceIDOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.PlaceModel)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPOSTV1PlacesPlaceIDBadRequest creates a POSTV1PlacesPlaceIDBadRequest with default headers values
func NewPOSTV1PlacesPlaceIDBadRequest() *POSTV1PlacesPlaceIDBadRequest {
	return &POSTV1PlacesPlaceIDBadRequest{}
}

/*POSTV1PlacesPlaceIDBadRequest handles this case with default header values.

{placeId} is invalid.
*/
type POSTV1PlacesPlaceIDBadRequest struct {
}

func (o *POSTV1PlacesPlaceIDBadRequest) Error() string {
	return fmt.Sprintf("[POST /v1/places/{placeId}][%d] pOSTV1PlacesPlaceIdBadRequest ", 400)
}

func (o *POSTV1PlacesPlaceIDBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewPOSTV1PlacesPlaceIDUnauthorized creates a POSTV1PlacesPlaceIDUnauthorized with default headers values
func NewPOSTV1PlacesPlaceIDUnauthorized() *POSTV1PlacesPlaceIDUnauthorized {
	return &POSTV1PlacesPlaceIDUnauthorized{}
}

/*POSTV1PlacesPlaceIDUnauthorized handles this case with default header values.

Authenticated user is not authorized to manage this place.
*/
type POSTV1PlacesPlaceIDUnauthorized struct {
}

func (o *POSTV1PlacesPlaceIDUnauthorized) Error() string {
	return fmt.Sprintf("[POST /v1/places/{placeId}][%d] pOSTV1PlacesPlaceIdUnauthorized ", 401)
}

func (o *POSTV1PlacesPlaceIDUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
