// Code generated by go-swagger; DO NOT EDIT.

package places

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// New creates a new places API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) *Client {
	return &Client{transport: transport, formats: formats}
}

/*
Client for places API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

/*
PATCHV1PlacesPlaceID updates the place configuration for the place with the id place Id

Currently the only supported functionality for updating the configuration is around Name, and Description.
*/
func (a *Client) PATCHV1PlacesPlaceID(params *PATCHV1PlacesPlaceIDParams) (*PATCHV1PlacesPlaceIDOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewPATCHV1PlacesPlaceIDParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "PATCH_v1_places_placeId_",
		Method:             "PATCH",
		PathPattern:        "/v1/places/{placeId}",
		ProducesMediaTypes: []string{"application/json", "text/json"},
		ConsumesMediaTypes: []string{"application/json", "application/x-www-form-urlencoded", "text/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &PATCHV1PlacesPlaceIDReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	return result.(*PATCHV1PlacesPlaceIDOK), nil

}

/*
POSTV1PlacesPlaceID updates the place configuration for the place with the id place Id

Currently the only supported functionality for updating the configuration is around Name, and Description.
*/
func (a *Client) POSTV1PlacesPlaceID(params *POSTV1PlacesPlaceIDParams) (*POSTV1PlacesPlaceIDOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewPOSTV1PlacesPlaceIDParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "POST_v1_places_placeId_",
		Method:             "POST",
		PathPattern:        "/v1/places/{placeId}",
		ProducesMediaTypes: []string{"application/json", "text/json"},
		ConsumesMediaTypes: []string{"application/json", "application/x-www-form-urlencoded", "text/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &POSTV1PlacesPlaceIDReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	return result.(*POSTV1PlacesPlaceIDOK), nil

}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
