/* 
 * Roblox.Api.Inventory V1
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package swagger

// A model containing information about a {Roblox.UserAsset}
type CollectibleUserAssetModel struct {

	UserAssetId int64 `json:"userAssetId,omitempty"`

	SerialNumber int64 `json:"serialNumber,omitempty"`

	AssetId int64 `json:"assetId,omitempty"`

	Name string `json:"name,omitempty"`

	RecentAveragePrice int64 `json:"recentAveragePrice,omitempty"`

	OriginalPrice int64 `json:"originalPrice,omitempty"`

	AssetStock int64 `json:"assetStock,omitempty"`

	BuildersClubMembershipType string `json:"buildersClubMembershipType,omitempty"`
}
