/* 
 * Roblox.Api.Inventory V1
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package swagger

type CreatorContainer struct {

	CreatorId int64 `json:"CreatorId,omitempty"`

	CreatorType string `json:"CreatorType,omitempty"`

	Name string `json:"Name,omitempty"`
}
