/* 
 * Roblox.Api.Inventory V1
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package swagger

type ItemContainer struct {

	AssetId int64 `json:"AssetId,omitempty"`

	Name string `json:"Name,omitempty"`

	Price int64 `json:"Price,omitempty"`

	AbsoluteUrl string `json:"AbsoluteUrl,omitempty"`

	AudioUrl string `json:"AudioUrl,omitempty"`
}
