/* 
 * Roblox.Api.Inventory V1
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package swagger

type ProductContainer struct {

	Id int64 `json:"Id,omitempty"`

	PriceInRobux int64 `json:"PriceInRobux,omitempty"`

	IsForSale bool `json:"IsForSale,omitempty"`

	IsPublicDomain bool `json:"IsPublicDomain,omitempty"`

	IsResellable bool `json:"IsResellable,omitempty"`

	IsLimited bool `json:"IsLimited,omitempty"`

	IsLimitedUnique bool `json:"IsLimitedUnique,omitempty"`

	SerialNumber int64 `json:"SerialNumber,omitempty"`

	IsRental bool `json:"IsRental,omitempty"`

	RentalDurationInHours int64 `json:"RentalDurationInHours,omitempty"`

	BcRequirement int32 `json:"BcRequirement,omitempty"`

	TotalPrivateSales int64 `json:"TotalPrivateSales,omitempty"`

	SellerId int64 `json:"SellerId,omitempty"`

	SellerName string `json:"SellerName,omitempty"`

	LowestPrivateSaleUserAssetId int64 `json:"LowestPrivateSaleUserAssetId,omitempty"`

	IsXboxExclusiveItem bool `json:"IsXboxExclusiveItem,omitempty"`

	OffsaleDeadline string `json:"OffsaleDeadline,omitempty"`
}
