/* 
 * Roblox.Api.Inventory V1
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package swagger

import (
	"time"
)

// A model containing information about a {Roblox.UserAsset}
type UserAssetModel struct {

	UserAssetId int64 `json:"userAssetId,omitempty"`

	SerialNumber int64 `json:"serialNumber,omitempty"`

	Owner UserModel `json:"owner,omitempty"`

	Created time.Time `json:"created,omitempty"`

	Updated time.Time `json:"updated,omitempty"`
}
