// Code generated by go-swagger; DO NOT EDIT.

package game_templates

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// New creates a new game templates API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) *Client {
	return &Client{transport: transport, formats: formats}
}

/*
Client for game templates API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

/*
GETV1Gametemplates gets a page of templates that can be used to start off making games

Templates subject to change without notice.
Sort order of templates specified by Roblox.
*/
func (a *Client) GETV1Gametemplates(params *GETV1GametemplatesParams) (*GETV1GametemplatesOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGETV1GametemplatesParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "GET_v1_gametemplates",
		Method:             "GET",
		PathPattern:        "/v1/gametemplates",
		ProducesMediaTypes: []string{"application/json", "text/json"},
		ConsumesMediaTypes: []string{""},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &GETV1GametemplatesReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	return result.(*GETV1GametemplatesOK), nil

}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
