/* 
 * Roblox.Api.Authentication V1
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package swagger

// A response model for unlocking account pin
type AccountPinResponseModel struct {

	// Returns the number of seconds left the account pin is unlocked until.
	UnlockedUntil float64 `json:"unlockedUntil,omitempty"`
}
