/* 
 * Roblox.Api.Authentication V1
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package swagger

// A class representing the status of Account Pin.
type AccountPinStatusResponseModel struct {

	// Gets or sets a value indicating whether this account pin is enabled.
	IsEnabled bool `json:"isEnabled,omitempty"`

	// Returns the number of seconds left the account pin is unlocked until.
	UnlockedUntil float64 `json:"unlockedUntil,omitempty"`
}
