/* 
 * Roblox.Api.Authentication V1
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package swagger

// A request model to get if an email is valid
type EmailValidationRequestModel struct {

	// Gets or sets the email to check for validation
	Email string `json:"email,omitempty"`
}
