/* 
 * Roblox.Api.Authentication V1
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package swagger

// A model containing information of social auth provider.
type ProviderInfoModel struct {

	// The social auth provider type.
	Provider string `json:"provider,omitempty"`

	// The social User ID.
	SocialUid string `json:"socialUid,omitempty"`
}
