/* 
 * Roblox.Api.Authentication V1
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package swagger

// The response model containing information about a two step verification challenge
type TwoStepVerificationSentResponse struct {

	// The media type the two step verification code was sent on
	MediaType string `json:"mediaType,omitempty"`

	// The two step verification ticket
	Ticket string `json:"ticket,omitempty"`
}
