/* 
 * Roblox.Api.Authentication V1
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package swagger

// A request model that contains information needed to verify with two step verification
type TwoStepVerificationVerifyRequestModel struct {

	// The username of the user the ticket belongs to
	Username string `json:"username,omitempty"`

	// The ticket
	Ticket string `json:"ticket,omitempty"`

	// The two step verification code
	Code string `json:"code,omitempty"`

	// Whether or not to remember the device for two step verification.
	RememberDevice bool `json:"rememberDevice,omitempty"`

	// The {Roblox.Platform.TwoStepVerification.TwoStepVerificationActionType} to verify.
	ActionType string `json:"actionType,omitempty"`
}
