/* 
 * Roblox.Api.Authentication V1
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package swagger

// A request model that holds two step verification ticket information
type TwoStepVerificationTicketRequestModel struct {

	// The username of the user the ticket belongs to
	Username string `json:"username,omitempty"`

	// The ticket
	Ticket string `json:"ticket,omitempty"`

	// The {Roblox.Platform.TwoStepVerification.TwoStepVerificationActionType} to request.
	ActionType string `json:"actionType,omitempty"`
}
