// Code generated by go-swagger; DO NOT EDIT.

package saml

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGETV1SamlMetadataParams creates a new GETV1SamlMetadataParams object
// with the default values initialized.
func NewGETV1SamlMetadataParams() *GETV1SamlMetadataParams {

	return &GETV1SamlMetadataParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGETV1SamlMetadataParamsWithTimeout creates a new GETV1SamlMetadataParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGETV1SamlMetadataParamsWithTimeout(timeout time.Duration) *GETV1SamlMetadataParams {

	return &GETV1SamlMetadataParams{

		timeout: timeout,
	}
}

// NewGETV1SamlMetadataParamsWithContext creates a new GETV1SamlMetadataParams object
// with the default values initialized, and the ability to set a context for a request
func NewGETV1SamlMetadataParamsWithContext(ctx context.Context) *GETV1SamlMetadataParams {

	return &GETV1SamlMetadataParams{

		Context: ctx,
	}
}

// NewGETV1SamlMetadataParamsWithHTTPClient creates a new GETV1SamlMetadataParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGETV1SamlMetadataParamsWithHTTPClient(client *http.Client) *GETV1SamlMetadataParams {

	return &GETV1SamlMetadataParams{
		HTTPClient: client,
	}
}

/*GETV1SamlMetadataParams contains all the parameters to send to the API endpoint
for the g e t v1 saml metadata operation typically these are written to a http.Request
*/
type GETV1SamlMetadataParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the g e t v1 saml metadata params
func (o *GETV1SamlMetadataParams) WithTimeout(timeout time.Duration) *GETV1SamlMetadataParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the g e t v1 saml metadata params
func (o *GETV1SamlMetadataParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the g e t v1 saml metadata params
func (o *GETV1SamlMetadataParams) WithContext(ctx context.Context) *GETV1SamlMetadataParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the g e t v1 saml metadata params
func (o *GETV1SamlMetadataParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the g e t v1 saml metadata params
func (o *GETV1SamlMetadataParams) WithHTTPClient(client *http.Client) *GETV1SamlMetadataParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the g e t v1 saml metadata params
func (o *GETV1SamlMetadataParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GETV1SamlMetadataParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
