// Code generated by go-swagger; DO NOT EDIT.

package saml

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/janberktold/go-roblox/auth/models"
)

// POSTV1SamlLoginReader is a Reader for the POSTV1SamlLogin structure.
type POSTV1SamlLoginReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *POSTV1SamlLoginReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewPOSTV1SamlLoginOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 302:
		result := NewPOSTV1SamlLoginFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 307:
		result := NewPOSTV1SamlLoginTemporaryRedirect()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewPOSTV1SamlLoginOK creates a POSTV1SamlLoginOK with default headers values
func NewPOSTV1SamlLoginOK() *POSTV1SamlLoginOK {
	return &POSTV1SamlLoginOK{}
}

/*POSTV1SamlLoginOK handles this case with default header values.

SAML2 response XML
*/
type POSTV1SamlLoginOK struct {
	Payload models.SamlAuthenticationResult
}

func (o *POSTV1SamlLoginOK) Error() string {
	return fmt.Sprintf("[POST /v1/saml/login][%d] pOSTV1SamlLoginOK  %+v", 200, o.Payload)
}

func (o *POSTV1SamlLoginOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPOSTV1SamlLoginFound creates a POSTV1SamlLoginFound with default headers values
func NewPOSTV1SamlLoginFound() *POSTV1SamlLoginFound {
	return &POSTV1SamlLoginFound{}
}

/*POSTV1SamlLoginFound handles this case with default header values.

An error occurred durring authentication. Redirects to www
*/
type POSTV1SamlLoginFound struct {
}

func (o *POSTV1SamlLoginFound) Error() string {
	return fmt.Sprintf("[POST /v1/saml/login][%d] pOSTV1SamlLoginFound ", 302)
}

func (o *POSTV1SamlLoginFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewPOSTV1SamlLoginTemporaryRedirect creates a POSTV1SamlLoginTemporaryRedirect with default headers values
func NewPOSTV1SamlLoginTemporaryRedirect() *POSTV1SamlLoginTemporaryRedirect {
	return &POSTV1SamlLoginTemporaryRedirect{}
}

/*POSTV1SamlLoginTemporaryRedirect handles this case with default header values.

Temporary redirect to www if the user is unauthenticated.
*/
type POSTV1SamlLoginTemporaryRedirect struct {
}

func (o *POSTV1SamlLoginTemporaryRedirect) Error() string {
	return fmt.Sprintf("[POST /v1/saml/login][%d] pOSTV1SamlLoginTemporaryRedirect ", 307)
}

func (o *POSTV1SamlLoginTemporaryRedirect) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
