// Code generated by go-swagger; DO NOT EDIT.

package amazon

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/janberktold/go-roblox/billing/models"
)

// NewPOSTV1AmazonPurchaseParams creates a new POSTV1AmazonPurchaseParams object
// with the default values initialized.
func NewPOSTV1AmazonPurchaseParams() *POSTV1AmazonPurchaseParams {
	var ()
	return &POSTV1AmazonPurchaseParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPOSTV1AmazonPurchaseParamsWithTimeout creates a new POSTV1AmazonPurchaseParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPOSTV1AmazonPurchaseParamsWithTimeout(timeout time.Duration) *POSTV1AmazonPurchaseParams {
	var ()
	return &POSTV1AmazonPurchaseParams{

		timeout: timeout,
	}
}

// NewPOSTV1AmazonPurchaseParamsWithContext creates a new POSTV1AmazonPurchaseParams object
// with the default values initialized, and the ability to set a context for a request
func NewPOSTV1AmazonPurchaseParamsWithContext(ctx context.Context) *POSTV1AmazonPurchaseParams {
	var ()
	return &POSTV1AmazonPurchaseParams{

		Context: ctx,
	}
}

// NewPOSTV1AmazonPurchaseParamsWithHTTPClient creates a new POSTV1AmazonPurchaseParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPOSTV1AmazonPurchaseParamsWithHTTPClient(client *http.Client) *POSTV1AmazonPurchaseParams {
	var ()
	return &POSTV1AmazonPurchaseParams{
		HTTPClient: client,
	}
}

/*POSTV1AmazonPurchaseParams contains all the parameters to send to the API endpoint
for the p o s t v1 amazon purchase operation typically these are written to a http.Request
*/
type POSTV1AmazonPurchaseParams struct {

	/*AmazonStorePurchaseModel
	  Amazon Store Purchase Model

	*/
	AmazonStorePurchaseModel *models.AmazonStorePurchaseModel

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the p o s t v1 amazon purchase params
func (o *POSTV1AmazonPurchaseParams) WithTimeout(timeout time.Duration) *POSTV1AmazonPurchaseParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the p o s t v1 amazon purchase params
func (o *POSTV1AmazonPurchaseParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the p o s t v1 amazon purchase params
func (o *POSTV1AmazonPurchaseParams) WithContext(ctx context.Context) *POSTV1AmazonPurchaseParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the p o s t v1 amazon purchase params
func (o *POSTV1AmazonPurchaseParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the p o s t v1 amazon purchase params
func (o *POSTV1AmazonPurchaseParams) WithHTTPClient(client *http.Client) *POSTV1AmazonPurchaseParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the p o s t v1 amazon purchase params
func (o *POSTV1AmazonPurchaseParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAmazonStorePurchaseModel adds the amazonStorePurchaseModel to the p o s t v1 amazon purchase params
func (o *POSTV1AmazonPurchaseParams) WithAmazonStorePurchaseModel(amazonStorePurchaseModel *models.AmazonStorePurchaseModel) *POSTV1AmazonPurchaseParams {
	o.SetAmazonStorePurchaseModel(amazonStorePurchaseModel)
	return o
}

// SetAmazonStorePurchaseModel adds the amazonStorePurchaseModel to the p o s t v1 amazon purchase params
func (o *POSTV1AmazonPurchaseParams) SetAmazonStorePurchaseModel(amazonStorePurchaseModel *models.AmazonStorePurchaseModel) {
	o.AmazonStorePurchaseModel = amazonStorePurchaseModel
}

// WriteToRequest writes these params to a swagger request
func (o *POSTV1AmazonPurchaseParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.AmazonStorePurchaseModel != nil {
		if err := r.SetBodyParam(o.AmazonStorePurchaseModel); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
