// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// APIPageResponseUserResponse Api page response user response
// swagger:model ApiPageResponse[UserResponse]

type APIPageResponseUserResponse struct {

	// data
	Data APIPageResponseUserResponseData `json:"data"`

	// next page cursor
	NextPageCursor string `json:"nextPageCursor,omitempty"`

	// previous page cursor
	PreviousPageCursor string `json:"previousPageCursor,omitempty"`
}

/* polymorph ApiPageResponse[UserResponse] data false */

/* polymorph ApiPageResponse[UserResponse] nextPageCursor false */

/* polymorph ApiPageResponse[UserResponse] previousPageCursor false */

// Validate validates this Api page response user response
func (m *APIPageResponseUserResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *APIPageResponseUserResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *APIPageResponseUserResponse) UnmarshalBinary(b []byte) error {
	var res APIPageResponseUserResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
