// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// APIArrayResponseGameTemplateModel Api array response game template model
// swagger:model ApiArrayResponse[GameTemplateModel]

type APIArrayResponseGameTemplateModel struct {

	// data
	Data APIArrayResponseGameTemplateModelData `json:"data"`
}

/* polymorph ApiArrayResponse[GameTemplateModel] data false */

// Validate validates this Api array response game template model
func (m *APIArrayResponseGameTemplateModel) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *APIArrayResponseGameTemplateModel) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *APIArrayResponseGameTemplateModel) UnmarshalBinary(b []byte) error {
	var res APIArrayResponseGameTemplateModel
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
