// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// APIMultiGetResponseUniverseModel Api multi get response universe model
// swagger:model ApiMultiGetResponse[UniverseModel]

type APIMultiGetResponseUniverseModel struct {

	// data
	Data APIMultiGetResponseUniverseModelData `json:"data"`
}

/* polymorph ApiMultiGetResponse[UniverseModel] data false */

// Validate validates this Api multi get response universe model
func (m *APIMultiGetResponseUniverseModel) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *APIMultiGetResponseUniverseModel) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *APIMultiGetResponseUniverseModel) UnmarshalBinary(b []byte) error {
	var res APIMultiGetResponseUniverseModel
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
