// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// GameTemplateModel game template model
// swagger:model GameTemplateModel

type GameTemplateModel struct {

	// game template type
	GameTemplateType string `json:"gameTemplateType,omitempty"`

	// has tutorials
	HasTutorials bool `json:"hasTutorials,omitempty"`

	// universe
	Universe *UniverseModel `json:"universe,omitempty"`
}

/* polymorph GameTemplateModel gameTemplateType false */

/* polymorph GameTemplateModel hasTutorials false */

/* polymorph GameTemplateModel universe false */

// Validate validates this game template model
func (m *GameTemplateModel) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateUniverse(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *GameTemplateModel) validateUniverse(formats strfmt.Registry) error {

	if swag.IsZero(m.Universe) { // not required
		return nil
	}

	if m.Universe != nil {

		if err := m.Universe.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("universe")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *GameTemplateModel) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *GameTemplateModel) UnmarshalBinary(b []byte) error {
	var res GameTemplateModel
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
