// Code generated by go-swagger; DO NOT EDIT.

package two_step_verification

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/janberktold/go-roblox/auth/models"
)

// POSTV1TwostepverificationVerifyReader is a Reader for the POSTV1TwostepverificationVerify structure.
type POSTV1TwostepverificationVerifyReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *POSTV1TwostepverificationVerifyReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewPOSTV1TwostepverificationVerifyOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewPOSTV1TwostepverificationVerifyBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 429:
		result := NewPOSTV1TwostepverificationVerifyTooManyRequests()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 503:
		result := NewPOSTV1TwostepverificationVerifyServiceUnavailable()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewPOSTV1TwostepverificationVerifyOK creates a POSTV1TwostepverificationVerifyOK with default headers values
func NewPOSTV1TwostepverificationVerifyOK() *POSTV1TwostepverificationVerifyOK {
	return &POSTV1TwostepverificationVerifyOK{}
}

/*POSTV1TwostepverificationVerifyOK handles this case with default header values.

Successfully verified two step verification code.
*/
type POSTV1TwostepverificationVerifyOK struct {
	Payload models.APIEmptyResponseModel
}

func (o *POSTV1TwostepverificationVerifyOK) Error() string {
	return fmt.Sprintf("[POST /v1/twostepverification/verify][%d] pOSTV1TwostepverificationVerifyOK  %+v", 200, o.Payload)
}

func (o *POSTV1TwostepverificationVerifyOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPOSTV1TwostepverificationVerifyBadRequest creates a POSTV1TwostepverificationVerifyBadRequest with default headers values
func NewPOSTV1TwostepverificationVerifyBadRequest() *POSTV1TwostepverificationVerifyBadRequest {
	return &POSTV1TwostepverificationVerifyBadRequest{}
}

/*POSTV1TwostepverificationVerifyBadRequest handles this case with default header values.

{Roblox.Api.Authentication.ResponseEnums.TwoStepVerificationErrors.InvalidUser}
            OR
            {Roblox.Api.Authentication.ResponseEnums.TwoStepVerificationErrors.InvalidTicket}
            OR
            {Roblox.Api.Authentication.ResponseEnums.TwoStepVerificationErrors.InvalidCode}
            OR
            {Roblox.Api.Authentication.ResponseEnums.TwoStepVerificationErrors.InvalidAction}
*/
type POSTV1TwostepverificationVerifyBadRequest struct {
}

func (o *POSTV1TwostepverificationVerifyBadRequest) Error() string {
	return fmt.Sprintf("[POST /v1/twostepverification/verify][%d] pOSTV1TwostepverificationVerifyBadRequest ", 400)
}

func (o *POSTV1TwostepverificationVerifyBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewPOSTV1TwostepverificationVerifyTooManyRequests creates a POSTV1TwostepverificationVerifyTooManyRequests with default headers values
func NewPOSTV1TwostepverificationVerifyTooManyRequests() *POSTV1TwostepverificationVerifyTooManyRequests {
	return &POSTV1TwostepverificationVerifyTooManyRequests{}
}

/*POSTV1TwostepverificationVerifyTooManyRequests handles this case with default header values.

{Roblox.Api.Authentication.ResponseEnums.TwoStepVerificationErrors.Flooded}
*/
type POSTV1TwostepverificationVerifyTooManyRequests struct {
}

func (o *POSTV1TwostepverificationVerifyTooManyRequests) Error() string {
	return fmt.Sprintf("[POST /v1/twostepverification/verify][%d] pOSTV1TwostepverificationVerifyTooManyRequests ", 429)
}

func (o *POSTV1TwostepverificationVerifyTooManyRequests) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewPOSTV1TwostepverificationVerifyServiceUnavailable creates a POSTV1TwostepverificationVerifyServiceUnavailable with default headers values
func NewPOSTV1TwostepverificationVerifyServiceUnavailable() *POSTV1TwostepverificationVerifyServiceUnavailable {
	return &POSTV1TwostepverificationVerifyServiceUnavailable{}
}

/*POSTV1TwostepverificationVerifyServiceUnavailable handles this case with default header values.

{Roblox.Api.Authentication.ResponseEnums.TwoStepVerificationErrors.FeatureDisabled}
*/
type POSTV1TwostepverificationVerifyServiceUnavailable struct {
}

func (o *POSTV1TwostepverificationVerifyServiceUnavailable) Error() string {
	return fmt.Sprintf("[POST /v1/twostepverification/verify][%d] pOSTV1TwostepverificationVerifyServiceUnavailable ", 503)
}

func (o *POSTV1TwostepverificationVerifyServiceUnavailable) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
