// Code generated by go-swagger; DO NOT EDIT.

package two_step_verification

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/janberktold/go-roblox/auth/models"
)

// NewPOSTV1TwostepverificationVerifyParams creates a new POSTV1TwostepverificationVerifyParams object
// with the default values initialized.
func NewPOSTV1TwostepverificationVerifyParams() *POSTV1TwostepverificationVerifyParams {
	var ()
	return &POSTV1TwostepverificationVerifyParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPOSTV1TwostepverificationVerifyParamsWithTimeout creates a new POSTV1TwostepverificationVerifyParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPOSTV1TwostepverificationVerifyParamsWithTimeout(timeout time.Duration) *POSTV1TwostepverificationVerifyParams {
	var ()
	return &POSTV1TwostepverificationVerifyParams{

		timeout: timeout,
	}
}

// NewPOSTV1TwostepverificationVerifyParamsWithContext creates a new POSTV1TwostepverificationVerifyParams object
// with the default values initialized, and the ability to set a context for a request
func NewPOSTV1TwostepverificationVerifyParamsWithContext(ctx context.Context) *POSTV1TwostepverificationVerifyParams {
	var ()
	return &POSTV1TwostepverificationVerifyParams{

		Context: ctx,
	}
}

// NewPOSTV1TwostepverificationVerifyParamsWithHTTPClient creates a new POSTV1TwostepverificationVerifyParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPOSTV1TwostepverificationVerifyParamsWithHTTPClient(client *http.Client) *POSTV1TwostepverificationVerifyParams {
	var ()
	return &POSTV1TwostepverificationVerifyParams{
		HTTPClient: client,
	}
}

/*POSTV1TwostepverificationVerifyParams contains all the parameters to send to the API endpoint
for the p o s t v1 twostepverification verify operation typically these are written to a http.Request
*/
type POSTV1TwostepverificationVerifyParams struct {

	/*Request
	  The request model containing information needed to verify with two step verification.

	*/
	Request *models.TwoStepVerificationVerifyRequestModel

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the p o s t v1 twostepverification verify params
func (o *POSTV1TwostepverificationVerifyParams) WithTimeout(timeout time.Duration) *POSTV1TwostepverificationVerifyParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the p o s t v1 twostepverification verify params
func (o *POSTV1TwostepverificationVerifyParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the p o s t v1 twostepverification verify params
func (o *POSTV1TwostepverificationVerifyParams) WithContext(ctx context.Context) *POSTV1TwostepverificationVerifyParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the p o s t v1 twostepverification verify params
func (o *POSTV1TwostepverificationVerifyParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the p o s t v1 twostepverification verify params
func (o *POSTV1TwostepverificationVerifyParams) WithHTTPClient(client *http.Client) *POSTV1TwostepverificationVerifyParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the p o s t v1 twostepverification verify params
func (o *POSTV1TwostepverificationVerifyParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithRequest adds the request to the p o s t v1 twostepverification verify params
func (o *POSTV1TwostepverificationVerifyParams) WithRequest(request *models.TwoStepVerificationVerifyRequestModel) *POSTV1TwostepverificationVerifyParams {
	o.SetRequest(request)
	return o
}

// SetRequest adds the request to the p o s t v1 twostepverification verify params
func (o *POSTV1TwostepverificationVerifyParams) SetRequest(request *models.TwoStepVerificationVerifyRequestModel) {
	o.Request = request
}

// WriteToRequest writes these params to a swagger request
func (o *POSTV1TwostepverificationVerifyParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Request != nil {
		if err := r.SetBodyParam(o.Request); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
