// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// APIPageResponseCollectibleUserAssetModel Api page response collectible user asset model
// swagger:model ApiPageResponse[CollectibleUserAssetModel]

type APIPageResponseCollectibleUserAssetModel struct {

	// data
	Data APIPageResponseCollectibleUserAssetModelData `json:"data"`

	// next page cursor
	NextPageCursor string `json:"nextPageCursor,omitempty"`

	// previous page cursor
	PreviousPageCursor string `json:"previousPageCursor,omitempty"`
}

/* polymorph ApiPageResponse[CollectibleUserAssetModel] data false */

/* polymorph ApiPageResponse[CollectibleUserAssetModel] nextPageCursor false */

/* polymorph ApiPageResponse[CollectibleUserAssetModel] previousPageCursor false */

// Validate validates this Api page response collectible user asset model
func (m *APIPageResponseCollectibleUserAssetModel) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *APIPageResponseCollectibleUserAssetModel) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *APIPageResponseCollectibleUserAssetModel) UnmarshalBinary(b []byte) error {
	var res APIPageResponseCollectibleUserAssetModel
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
