// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// AssetIDListModel A model that contains a list of asset ids
// swagger:model AssetIdListModel

type AssetIDListModel struct {

	// asset ids
	AssetIds []int64 `json:"assetIds"`
}

/* polymorph AssetIdListModel assetIds false */

// Validate validates this asset Id list model
func (m *AssetIDListModel) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateAssetIds(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *AssetIDListModel) validateAssetIds(formats strfmt.Registry) error {

	if swag.IsZero(m.AssetIds) { // not required
		return nil
	}

	return nil
}

// MarshalBinary interface implementation
func (m *AssetIDListModel) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *AssetIDListModel) UnmarshalBinary(b []byte) error {
	var res AssetIDListModel
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
