// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// ItemContainer item container
// swagger:model ItemContainer

type ItemContainer struct {

	// absolute Url
	AbsoluteURL string `json:"AbsoluteUrl,omitempty"`

	// asset Id
	AssetID int64 `json:"AssetId,omitempty"`

	// audio Url
	AudioURL string `json:"AudioUrl,omitempty"`

	// name
	Name string `json:"Name,omitempty"`

	// price
	Price int64 `json:"Price,omitempty"`
}

/* polymorph ItemContainer AbsoluteUrl false */

/* polymorph ItemContainer AssetId false */

/* polymorph ItemContainer AudioUrl false */

/* polymorph ItemContainer Name false */

/* polymorph ItemContainer Price false */

// Validate validates this item container
func (m *ItemContainer) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *ItemContainer) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ItemContainer) UnmarshalBinary(b []byte) error {
	var res ItemContainer
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
