// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// AccountPinRequestModel A request model to accept pin.
// swagger:model AccountPinRequestModel

type AccountPinRequestModel struct {

	// Gets or sets the pin.
	Pin string `json:"pin,omitempty"`
}

/* polymorph AccountPinRequestModel pin false */

// Validate validates this account pin request model
func (m *AccountPinRequestModel) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *AccountPinRequestModel) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *AccountPinRequestModel) UnmarshalBinary(b []byte) error {
	var res AccountPinRequestModel
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
