// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// ProviderInfoModel A model containing information of social auth provider.
// swagger:model ProviderInfoModel

type ProviderInfoModel struct {

	// The social auth provider type.
	Provider string `json:"provider,omitempty"`

	// The social User ID.
	SocialUID string `json:"socialUid,omitempty"`
}

/* polymorph ProviderInfoModel provider false */

/* polymorph ProviderInfoModel socialUid false */

// Validate validates this provider info model
func (m *ProviderInfoModel) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *ProviderInfoModel) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ProviderInfoModel) UnmarshalBinary(b []byte) error {
	var res ProviderInfoModel
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
