// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// RecommendedUsernameRequestModel A request model to generated a username
// swagger:model RecommendedUsernameRequestModel

type RecommendedUsernameRequestModel struct {

	// Gets or sets the birth day.
	Birthday strfmt.DateTime `json:"birthday,omitempty"`

	// Gets or sets the username to use as the base username provided by the user
	Username string `json:"username,omitempty"`
}

/* polymorph RecommendedUsernameRequestModel birthday false */

/* polymorph RecommendedUsernameRequestModel username false */

// Validate validates this recommended username request model
func (m *RecommendedUsernameRequestModel) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *RecommendedUsernameRequestModel) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *RecommendedUsernameRequestModel) UnmarshalBinary(b []byte) error {
	var res RecommendedUsernameRequestModel
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
