// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// TwoStepVerificationSentResponse The response model containing information about a two step verification challenge
// swagger:model TwoStepVerificationSentResponse

type TwoStepVerificationSentResponse struct {

	// The media type the two step verification code was sent on
	MediaType string `json:"mediaType,omitempty"`

	// The two step verification ticket
	Ticket strfmt.UUID `json:"ticket,omitempty"`
}

/* polymorph TwoStepVerificationSentResponse mediaType false */

/* polymorph TwoStepVerificationSentResponse ticket false */

// Validate validates this two step verification sent response
func (m *TwoStepVerificationSentResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateMediaType(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

var twoStepVerificationSentResponseTypeMediaTypePropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["Email","SMS"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		twoStepVerificationSentResponseTypeMediaTypePropEnum = append(twoStepVerificationSentResponseTypeMediaTypePropEnum, v)
	}
}

const (
	// TwoStepVerificationSentResponseMediaTypeEmail captures enum value "Email"
	TwoStepVerificationSentResponseMediaTypeEmail string = "Email"
	// TwoStepVerificationSentResponseMediaTypeSMS captures enum value "SMS"
	TwoStepVerificationSentResponseMediaTypeSMS string = "SMS"
)

// prop value enum
func (m *TwoStepVerificationSentResponse) validateMediaTypeEnum(path, location string, value string) error {
	if err := validate.Enum(path, location, value, twoStepVerificationSentResponseTypeMediaTypePropEnum); err != nil {
		return err
	}
	return nil
}

func (m *TwoStepVerificationSentResponse) validateMediaType(formats strfmt.Registry) error {

	if swag.IsZero(m.MediaType) { // not required
		return nil
	}

	// value enum
	if err := m.validateMediaTypeEnum("mediaType", "body", m.MediaType); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *TwoStepVerificationSentResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *TwoStepVerificationSentResponse) UnmarshalBinary(b []byte) error {
	var res TwoStepVerificationSentResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
