// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// XboxConnectionModel A model containing information on whether the user is a Xbox user.
// swagger:model XboxConnectionModel

type XboxConnectionModel struct {

	// Whether the current user has Xbox account connected.
	HasConnectedXboxAccount bool `json:"hasConnectedXboxAccount,omitempty"`
}

/* polymorph XboxConnectionModel hasConnectedXboxAccount false */

// Validate validates this xbox connection model
func (m *XboxConnectionModel) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *XboxConnectionModel) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *XboxConnectionModel) UnmarshalBinary(b []byte) error {
	var res XboxConnectionModel
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
