/* 
 * Roblox.Groups.Api V1
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package swagger

import (
	"time"
)

// A response model for group wall post information
type GroupWallPostModel struct {

	// The group wall post Id.
	Id int32 `json:"id,omitempty"`

	// The user that posted the group wall post.
	Poster UserModel `json:"poster,omitempty"`

	// The group wall post body.
	Body string `json:"body,omitempty"`

	// When the group wall post was posted.
	Created time.Time `json:"created,omitempty"`

	// When the group wall post was last updated.
	Updated time.Time `json:"updated,omitempty"`
}
