/* 
 * Roblox.Api.Billing V1
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package swagger

// A model containing information about making a purchase through Apple store
type AppleStorePurchaseModel struct {

	// ProductId
	ProductId string `json:"productId,omitempty"`

	// Receipt
	Receipt string `json:"receipt,omitempty"`

	// Is the purchase a Retry
	IsRetry bool `json:"isRetry,omitempty"`
}
