/* 
 * Roblox.Api.Develop V1
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package swagger

// A model containing information about a place
type PlaceModel struct {

	UniverseId int64 `json:"universeId,omitempty"`

	Name string `json:"name,omitempty"`

	Description string `json:"description,omitempty"`

	Id int64 `json:"id,omitempty"`
}
