/* 
 * Roblox.Api.Develop V1
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package swagger

// Team create settings
type TeamCreateSettingsResponse struct {

	// Whether or not the universe should be enabled for team create
	IsEnabled bool `json:"isEnabled,omitempty"`
}
