// Code generated by go-swagger; DO NOT EDIT.

package xbox

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGETV1XboxConnectionParams creates a new GETV1XboxConnectionParams object
// with the default values initialized.
func NewGETV1XboxConnectionParams() *GETV1XboxConnectionParams {

	return &GETV1XboxConnectionParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGETV1XboxConnectionParamsWithTimeout creates a new GETV1XboxConnectionParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGETV1XboxConnectionParamsWithTimeout(timeout time.Duration) *GETV1XboxConnectionParams {

	return &GETV1XboxConnectionParams{

		timeout: timeout,
	}
}

// NewGETV1XboxConnectionParamsWithContext creates a new GETV1XboxConnectionParams object
// with the default values initialized, and the ability to set a context for a request
func NewGETV1XboxConnectionParamsWithContext(ctx context.Context) *GETV1XboxConnectionParams {

	return &GETV1XboxConnectionParams{

		Context: ctx,
	}
}

// NewGETV1XboxConnectionParamsWithHTTPClient creates a new GETV1XboxConnectionParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGETV1XboxConnectionParamsWithHTTPClient(client *http.Client) *GETV1XboxConnectionParams {

	return &GETV1XboxConnectionParams{
		HTTPClient: client,
	}
}

/*GETV1XboxConnectionParams contains all the parameters to send to the API endpoint
for the g e t v1 xbox connection operation typically these are written to a http.Request
*/
type GETV1XboxConnectionParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the g e t v1 xbox connection params
func (o *GETV1XboxConnectionParams) WithTimeout(timeout time.Duration) *GETV1XboxConnectionParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the g e t v1 xbox connection params
func (o *GETV1XboxConnectionParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the g e t v1 xbox connection params
func (o *GETV1XboxConnectionParams) WithContext(ctx context.Context) *GETV1XboxConnectionParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the g e t v1 xbox connection params
func (o *GETV1XboxConnectionParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the g e t v1 xbox connection params
func (o *GETV1XboxConnectionParams) WithHTTPClient(client *http.Client) *GETV1XboxConnectionParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the g e t v1 xbox connection params
func (o *GETV1XboxConnectionParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GETV1XboxConnectionParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
