// Code generated by go-swagger; DO NOT EDIT.

package xbox

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// New creates a new xbox API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) *Client {
	return &Client{transport: transport, formats: formats}
}

/*
Client for xbox API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

/*
GETV1XboxConnection checks if the current user has an xbox connected
*/
func (a *Client) GETV1XboxConnection(params *GETV1XboxConnectionParams) (*GETV1XboxConnectionOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGETV1XboxConnectionParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "GET_v1_xbox_connection",
		Method:             "GET",
		PathPattern:        "/v1/xbox/connection",
		ProducesMediaTypes: []string{"application/json", "text/json"},
		ConsumesMediaTypes: []string{""},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &GETV1XboxConnectionReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	return result.(*GETV1XboxConnectionOK), nil

}

/*
POSTV1XboxDisconnect unlinks the current r o b l o x account from the xbox live account
*/
func (a *Client) POSTV1XboxDisconnect(params *POSTV1XboxDisconnectParams) (*POSTV1XboxDisconnectOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewPOSTV1XboxDisconnectParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "POST_v1_xbox_disconnect",
		Method:             "POST",
		PathPattern:        "/v1/xbox/disconnect",
		ProducesMediaTypes: []string{"application/json", "text/json"},
		ConsumesMediaTypes: []string{""},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &POSTV1XboxDisconnectReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	return result.(*POSTV1XboxDisconnectOK), nil

}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
