// Code generated by go-swagger; DO NOT EDIT.

package user

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/janberktold/go-roblox/develop/models"
)

// GETV1UserGroupsCanmanageReader is a Reader for the GETV1UserGroupsCanmanage structure.
type GETV1UserGroupsCanmanageReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GETV1UserGroupsCanmanageReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGETV1UserGroupsCanmanageOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGETV1UserGroupsCanmanageOK creates a GETV1UserGroupsCanmanageOK with default headers values
func NewGETV1UserGroupsCanmanageOK() *GETV1UserGroupsCanmanageOK {
	return &GETV1UserGroupsCanmanageOK{}
}

/*GETV1UserGroupsCanmanageOK handles this case with default header values.

GETV1UserGroupsCanmanageOK g e t v1 user groups canmanage o k
*/
type GETV1UserGroupsCanmanageOK struct {
	Payload *models.APIArrayResponseGroupModel
}

func (o *GETV1UserGroupsCanmanageOK) Error() string {
	return fmt.Sprintf("[GET /v1/user/groups/canmanage][%d] gETV1UserGroupsCanmanageOK  %+v", 200, o.Payload)
}

func (o *GETV1UserGroupsCanmanageOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIArrayResponseGroupModel)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
