// Code generated by go-swagger; DO NOT EDIT.

package user

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGETV1UserStudiodataParams creates a new GETV1UserStudiodataParams object
// with the default values initialized.
func NewGETV1UserStudiodataParams() *GETV1UserStudiodataParams {
	var ()
	return &GETV1UserStudiodataParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGETV1UserStudiodataParamsWithTimeout creates a new GETV1UserStudiodataParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGETV1UserStudiodataParamsWithTimeout(timeout time.Duration) *GETV1UserStudiodataParams {
	var ()
	return &GETV1UserStudiodataParams{

		timeout: timeout,
	}
}

// NewGETV1UserStudiodataParamsWithContext creates a new GETV1UserStudiodataParams object
// with the default values initialized, and the ability to set a context for a request
func NewGETV1UserStudiodataParamsWithContext(ctx context.Context) *GETV1UserStudiodataParams {
	var ()
	return &GETV1UserStudiodataParams{

		Context: ctx,
	}
}

// NewGETV1UserStudiodataParamsWithHTTPClient creates a new GETV1UserStudiodataParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGETV1UserStudiodataParamsWithHTTPClient(client *http.Client) *GETV1UserStudiodataParams {
	var ()
	return &GETV1UserStudiodataParams{
		HTTPClient: client,
	}
}

/*GETV1UserStudiodataParams contains all the parameters to send to the API endpoint
for the g e t v1 user studiodata operation typically these are written to a http.Request
*/
type GETV1UserStudiodataParams struct {

	/*ClientKey
	  A Key to find this data under. Optional.

	*/
	ClientKey *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the g e t v1 user studiodata params
func (o *GETV1UserStudiodataParams) WithTimeout(timeout time.Duration) *GETV1UserStudiodataParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the g e t v1 user studiodata params
func (o *GETV1UserStudiodataParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the g e t v1 user studiodata params
func (o *GETV1UserStudiodataParams) WithContext(ctx context.Context) *GETV1UserStudiodataParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the g e t v1 user studiodata params
func (o *GETV1UserStudiodataParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the g e t v1 user studiodata params
func (o *GETV1UserStudiodataParams) WithHTTPClient(client *http.Client) *GETV1UserStudiodataParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the g e t v1 user studiodata params
func (o *GETV1UserStudiodataParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithClientKey adds the clientKey to the g e t v1 user studiodata params
func (o *GETV1UserStudiodataParams) WithClientKey(clientKey *string) *GETV1UserStudiodataParams {
	o.SetClientKey(clientKey)
	return o
}

// SetClientKey adds the clientKey to the g e t v1 user studiodata params
func (o *GETV1UserStudiodataParams) SetClientKey(clientKey *string) {
	o.ClientKey = clientKey
}

// WriteToRequest writes these params to a swagger request
func (o *GETV1UserStudiodataParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.ClientKey != nil {

		// query param clientKey
		var qrClientKey string
		if o.ClientKey != nil {
			qrClientKey = *o.ClientKey
		}
		qClientKey := qrClientKey
		if qClientKey != "" {
			if err := r.SetQueryParam("clientKey", qClientKey); err != nil {
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
