// Code generated by go-swagger; DO NOT EDIT.

package user

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/janberktold/go-roblox/develop/models"
)

// GETV1UserUniversesReader is a Reader for the GETV1UserUniverses structure.
type GETV1UserUniversesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GETV1UserUniversesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGETV1UserUniversesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewGETV1UserUniversesBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGETV1UserUniversesOK creates a GETV1UserUniversesOK with default headers values
func NewGETV1UserUniversesOK() *GETV1UserUniversesOK {
	return &GETV1UserUniversesOK{}
}

/*GETV1UserUniversesOK handles this case with default header values.

GETV1UserUniversesOK g e t v1 user universes o k
*/
type GETV1UserUniversesOK struct {
	Payload *models.APIPageResponseUniverseModel
}

func (o *GETV1UserUniversesOK) Error() string {
	return fmt.Sprintf("[GET /v1/user/universes][%d] gETV1UserUniversesOK  %+v", 200, o.Payload)
}

func (o *GETV1UserUniversesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIPageResponseUniverseModel)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGETV1UserUniversesBadRequest creates a GETV1UserUniversesBadRequest with default headers values
func NewGETV1UserUniversesBadRequest() *GETV1UserUniversesBadRequest {
	return &GETV1UserUniversesBadRequest{}
}

/*GETV1UserUniversesBadRequest handles this case with default header values.

cursor is not valid.
*/
type GETV1UserUniversesBadRequest struct {
}

func (o *GETV1UserUniversesBadRequest) Error() string {
	return fmt.Sprintf("[GET /v1/user/universes][%d] gETV1UserUniversesBadRequest ", 400)
}

func (o *GETV1UserUniversesBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
