// Code generated by go-swagger; DO NOT EDIT.

package account_pin

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/janberktold/go-roblox/auth/models"
)

// POSTV1AccountPinReader is a Reader for the POSTV1AccountPin structure.
type POSTV1AccountPinReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *POSTV1AccountPinReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewPOSTV1AccountPinOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewPOSTV1AccountPinOK creates a POSTV1AccountPinOK with default headers values
func NewPOSTV1AccountPinOK() *POSTV1AccountPinOK {
	return &POSTV1AccountPinOK{}
}

/*POSTV1AccountPinOK handles this case with default header values.

OK
*/
type POSTV1AccountPinOK struct {
	Payload *models.APISuccessResponse
}

func (o *POSTV1AccountPinOK) Error() string {
	return fmt.Sprintf("[POST /v1/account/pin][%d] pOSTV1AccountPinOK  %+v", 200, o.Payload)
}

func (o *POSTV1AccountPinOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APISuccessResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
