// Code generated by go-swagger; DO NOT EDIT.

package account_pin

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/janberktold/go-roblox/auth/models"
)

// POSTV1AccountPinLockReader is a Reader for the POSTV1AccountPinLock structure.
type POSTV1AccountPinLockReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *POSTV1AccountPinLockReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewPOSTV1AccountPinLockOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewPOSTV1AccountPinLockOK creates a POSTV1AccountPinLockOK with default headers values
func NewPOSTV1AccountPinLockOK() *POSTV1AccountPinLockOK {
	return &POSTV1AccountPinLockOK{}
}

/*POSTV1AccountPinLockOK handles this case with default header values.

OK
*/
type POSTV1AccountPinLockOK struct {
	Payload *models.APISuccessResponse
}

func (o *POSTV1AccountPinLockOK) Error() string {
	return fmt.Sprintf("[POST /v1/account/pin/lock][%d] pOSTV1AccountPinLockOK  %+v", 200, o.Payload)
}

func (o *POSTV1AccountPinLockOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APISuccessResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
