// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// GooglePlayPurchaseModel A model containing information about making a purchase through Google Play
// swagger:model GooglePlayPurchaseModel

type GooglePlayPurchaseModel struct {

	// Is the purchase a Retry
	IsRetry bool `json:"isRetry,omitempty"`

	// The Order Id
	OrderID string `json:"orderId,omitempty"`

	// Package Name
	PackageName string `json:"packageName,omitempty"`

	// ProductId
	ProductID string `json:"productId,omitempty"`

	// Token
	Token string `json:"token,omitempty"`
}

/* polymorph GooglePlayPurchaseModel isRetry false */

/* polymorph GooglePlayPurchaseModel orderId false */

/* polymorph GooglePlayPurchaseModel packageName false */

/* polymorph GooglePlayPurchaseModel productId false */

/* polymorph GooglePlayPurchaseModel token false */

// Validate validates this google play purchase model
func (m *GooglePlayPurchaseModel) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *GooglePlayPurchaseModel) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *GooglePlayPurchaseModel) UnmarshalBinary(b []byte) error {
	var res GooglePlayPurchaseModel
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
