// Code generated by go-swagger; DO NOT EDIT.

package universe_settings

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/janberktold/go-roblox/develop/models"
)

// NewPATCHV1UniversesUniverseIDConfigurationParams creates a new PATCHV1UniversesUniverseIDConfigurationParams object
// with the default values initialized.
func NewPATCHV1UniversesUniverseIDConfigurationParams() *PATCHV1UniversesUniverseIDConfigurationParams {
	var ()
	return &PATCHV1UniversesUniverseIDConfigurationParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPATCHV1UniversesUniverseIDConfigurationParamsWithTimeout creates a new PATCHV1UniversesUniverseIDConfigurationParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPATCHV1UniversesUniverseIDConfigurationParamsWithTimeout(timeout time.Duration) *PATCHV1UniversesUniverseIDConfigurationParams {
	var ()
	return &PATCHV1UniversesUniverseIDConfigurationParams{

		timeout: timeout,
	}
}

// NewPATCHV1UniversesUniverseIDConfigurationParamsWithContext creates a new PATCHV1UniversesUniverseIDConfigurationParams object
// with the default values initialized, and the ability to set a context for a request
func NewPATCHV1UniversesUniverseIDConfigurationParamsWithContext(ctx context.Context) *PATCHV1UniversesUniverseIDConfigurationParams {
	var ()
	return &PATCHV1UniversesUniverseIDConfigurationParams{

		Context: ctx,
	}
}

// NewPATCHV1UniversesUniverseIDConfigurationParamsWithHTTPClient creates a new PATCHV1UniversesUniverseIDConfigurationParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPATCHV1UniversesUniverseIDConfigurationParamsWithHTTPClient(client *http.Client) *PATCHV1UniversesUniverseIDConfigurationParams {
	var ()
	return &PATCHV1UniversesUniverseIDConfigurationParams{
		HTTPClient: client,
	}
}

/*PATCHV1UniversesUniverseIDConfigurationParams contains all the parameters to send to the API endpoint
for the p a t c h v1 universes universe Id configuration operation typically these are written to a http.Request
*/
type PATCHV1UniversesUniverseIDConfigurationParams struct {

	/*Model
	  The {Roblox.Api.Develop.Models.UniverseSettingsRequest} model.

	*/
	Model *models.UniverseSettingsRequest
	/*UniverseID
	  The universeId.

	*/
	UniverseID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the p a t c h v1 universes universe Id configuration params
func (o *PATCHV1UniversesUniverseIDConfigurationParams) WithTimeout(timeout time.Duration) *PATCHV1UniversesUniverseIDConfigurationParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the p a t c h v1 universes universe Id configuration params
func (o *PATCHV1UniversesUniverseIDConfigurationParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the p a t c h v1 universes universe Id configuration params
func (o *PATCHV1UniversesUniverseIDConfigurationParams) WithContext(ctx context.Context) *PATCHV1UniversesUniverseIDConfigurationParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the p a t c h v1 universes universe Id configuration params
func (o *PATCHV1UniversesUniverseIDConfigurationParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the p a t c h v1 universes universe Id configuration params
func (o *PATCHV1UniversesUniverseIDConfigurationParams) WithHTTPClient(client *http.Client) *PATCHV1UniversesUniverseIDConfigurationParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the p a t c h v1 universes universe Id configuration params
func (o *PATCHV1UniversesUniverseIDConfigurationParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithModel adds the model to the p a t c h v1 universes universe Id configuration params
func (o *PATCHV1UniversesUniverseIDConfigurationParams) WithModel(model *models.UniverseSettingsRequest) *PATCHV1UniversesUniverseIDConfigurationParams {
	o.SetModel(model)
	return o
}

// SetModel adds the model to the p a t c h v1 universes universe Id configuration params
func (o *PATCHV1UniversesUniverseIDConfigurationParams) SetModel(model *models.UniverseSettingsRequest) {
	o.Model = model
}

// WithUniverseID adds the universeID to the p a t c h v1 universes universe Id configuration params
func (o *PATCHV1UniversesUniverseIDConfigurationParams) WithUniverseID(universeID int64) *PATCHV1UniversesUniverseIDConfigurationParams {
	o.SetUniverseID(universeID)
	return o
}

// SetUniverseID adds the universeId to the p a t c h v1 universes universe Id configuration params
func (o *PATCHV1UniversesUniverseIDConfigurationParams) SetUniverseID(universeID int64) {
	o.UniverseID = universeID
}

// WriteToRequest writes these params to a swagger request
func (o *PATCHV1UniversesUniverseIDConfigurationParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Model != nil {
		if err := r.SetBodyParam(o.Model); err != nil {
			return err
		}
	}

	// path param universeId
	if err := r.SetPathParam("universeId", swag.FormatInt64(o.UniverseID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
