// Code generated by go-swagger; DO NOT EDIT.

package universe_settings

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// New creates a new universe settings API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) *Client {
	return &Client{transport: transport, formats: formats}
}

/*
Client for universe settings API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

/*
GETV1UniversesUniverseIDConfiguration gets settings for an owned universe
*/
func (a *Client) GETV1UniversesUniverseIDConfiguration(params *GETV1UniversesUniverseIDConfigurationParams) (*GETV1UniversesUniverseIDConfigurationOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGETV1UniversesUniverseIDConfigurationParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "GET_v1_universes_universeId_configuration",
		Method:             "GET",
		PathPattern:        "/v1/universes/{universeId}/configuration",
		ProducesMediaTypes: []string{"application/json", "text/json"},
		ConsumesMediaTypes: []string{""},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &GETV1UniversesUniverseIDConfigurationReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	return result.(*GETV1UniversesUniverseIDConfigurationOK), nil

}

/*
PATCHV1UniversesUniverseIDConfiguration updates universe settings for an owned universe
*/
func (a *Client) PATCHV1UniversesUniverseIDConfiguration(params *PATCHV1UniversesUniverseIDConfigurationParams) (*PATCHV1UniversesUniverseIDConfigurationOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewPATCHV1UniversesUniverseIDConfigurationParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "PATCH_v1_universes_universeId_configuration",
		Method:             "PATCH",
		PathPattern:        "/v1/universes/{universeId}/configuration",
		ProducesMediaTypes: []string{"application/json", "text/json"},
		ConsumesMediaTypes: []string{"application/json", "application/x-www-form-urlencoded", "text/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &PATCHV1UniversesUniverseIDConfigurationReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	return result.(*PATCHV1UniversesUniverseIDConfigurationOK), nil

}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
