// Code generated by go-swagger; DO NOT EDIT.

package groups

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/janberktold/go-roblox/develop/models"
)

// GETV1GroupsGroupIDUniversesReader is a Reader for the GETV1GroupsGroupIDUniverses structure.
type GETV1GroupsGroupIDUniversesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GETV1GroupsGroupIDUniversesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGETV1GroupsGroupIDUniversesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewGETV1GroupsGroupIDUniversesBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGETV1GroupsGroupIDUniversesOK creates a GETV1GroupsGroupIDUniversesOK with default headers values
func NewGETV1GroupsGroupIDUniversesOK() *GETV1GroupsGroupIDUniversesOK {
	return &GETV1GroupsGroupIDUniversesOK{}
}

/*GETV1GroupsGroupIDUniversesOK handles this case with default header values.

GETV1GroupsGroupIDUniversesOK g e t v1 groups group Id universes o k
*/
type GETV1GroupsGroupIDUniversesOK struct {
	Payload *models.APIPageResponseUniverseModel
}

func (o *GETV1GroupsGroupIDUniversesOK) Error() string {
	return fmt.Sprintf("[GET /v1/groups/{groupId}/universes][%d] gETV1GroupsGroupIdUniversesOK  %+v", 200, o.Payload)
}

func (o *GETV1GroupsGroupIDUniversesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIPageResponseUniverseModel)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGETV1GroupsGroupIDUniversesBadRequest creates a GETV1GroupsGroupIDUniversesBadRequest with default headers values
func NewGETV1GroupsGroupIDUniversesBadRequest() *GETV1GroupsGroupIDUniversesBadRequest {
	return &GETV1GroupsGroupIDUniversesBadRequest{}
}

/*GETV1GroupsGroupIDUniversesBadRequest handles this case with default header values.

Invalid {groupId}.
*/
type GETV1GroupsGroupIDUniversesBadRequest struct {
}

func (o *GETV1GroupsGroupIDUniversesBadRequest) Error() string {
	return fmt.Sprintf("[GET /v1/groups/{groupId}/universes][%d] gETV1GroupsGroupIdUniversesBadRequest ", 400)
}

func (o *GETV1GroupsGroupIDUniversesBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
