// Code generated by go-swagger; DO NOT EDIT.

package apple

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/janberktold/go-roblox/avatar/models"
)

// POSTV1ApplePurchaseReader is a Reader for the POSTV1ApplePurchase structure.
type POSTV1ApplePurchaseReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *POSTV1ApplePurchaseReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewPOSTV1ApplePurchaseOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewPOSTV1ApplePurchaseBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 401:
		result := NewPOSTV1ApplePurchaseUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewPOSTV1ApplePurchaseOK creates a POSTV1ApplePurchaseOK with default headers values
func NewPOSTV1ApplePurchaseOK() *POSTV1ApplePurchaseOK {
	return &POSTV1ApplePurchaseOK{}
}

/*POSTV1ApplePurchaseOK handles this case with default header values.

POSTV1ApplePurchaseOK p o s t v1 apple purchase o k
*/
type POSTV1ApplePurchaseOK struct {
	Payload models.APIEmptyResponseModel
}

func (o *POSTV1ApplePurchaseOK) Error() string {
	return fmt.Sprintf("[POST /v1/apple/purchase][%d] pOSTV1ApplePurchaseOK  %+v", 200, o.Payload)
}

func (o *POSTV1ApplePurchaseOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPOSTV1ApplePurchaseBadRequest creates a POSTV1ApplePurchaseBadRequest with default headers values
func NewPOSTV1ApplePurchaseBadRequest() *POSTV1ApplePurchaseBadRequest {
	return &POSTV1ApplePurchaseBadRequest{}
}

/*POSTV1ApplePurchaseBadRequest handles this case with default header values.

Service has thrown an uknown exception.
*/
type POSTV1ApplePurchaseBadRequest struct {
}

func (o *POSTV1ApplePurchaseBadRequest) Error() string {
	return fmt.Sprintf("[POST /v1/apple/purchase][%d] pOSTV1ApplePurchaseBadRequest ", 400)
}

func (o *POSTV1ApplePurchaseBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewPOSTV1ApplePurchaseUnauthorized creates a POSTV1ApplePurchaseUnauthorized with default headers values
func NewPOSTV1ApplePurchaseUnauthorized() *POSTV1ApplePurchaseUnauthorized {
	return &POSTV1ApplePurchaseUnauthorized{}
}

/*POSTV1ApplePurchaseUnauthorized handles this case with default header values.

Unauthorized to make request.
*/
type POSTV1ApplePurchaseUnauthorized struct {
}

func (o *POSTV1ApplePurchaseUnauthorized) Error() string {
	return fmt.Sprintf("[POST /v1/apple/purchase][%d] pOSTV1ApplePurchaseUnauthorized ", 401)
}

func (o *POSTV1ApplePurchaseUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
