// Code generated by go-swagger; DO NOT EDIT.

package universes

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/janberktold/go-roblox/develop/models"
)

// GETV1UniversesUniverseIDPermissionsReader is a Reader for the GETV1UniversesUniverseIDPermissions structure.
type GETV1UniversesUniverseIDPermissionsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GETV1UniversesUniverseIDPermissionsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGETV1UniversesUniverseIDPermissionsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewGETV1UniversesUniverseIDPermissionsBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGETV1UniversesUniverseIDPermissionsOK creates a GETV1UniversesUniverseIDPermissionsOK with default headers values
func NewGETV1UniversesUniverseIDPermissionsOK() *GETV1UniversesUniverseIDPermissionsOK {
	return &GETV1UniversesUniverseIDPermissionsOK{}
}

/*GETV1UniversesUniverseIDPermissionsOK handles this case with default header values.

GETV1UniversesUniverseIDPermissionsOK g e t v1 universes universe Id permissions o k
*/
type GETV1UniversesUniverseIDPermissionsOK struct {
	Payload *models.UniversePermissionsModel
}

func (o *GETV1UniversesUniverseIDPermissionsOK) Error() string {
	return fmt.Sprintf("[GET /v1/universes/{universeId}/permissions][%d] gETV1UniversesUniverseIdPermissionsOK  %+v", 200, o.Payload)
}

func (o *GETV1UniversesUniverseIDPermissionsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.UniversePermissionsModel)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGETV1UniversesUniverseIDPermissionsBadRequest creates a GETV1UniversesUniverseIDPermissionsBadRequest with default headers values
func NewGETV1UniversesUniverseIDPermissionsBadRequest() *GETV1UniversesUniverseIDPermissionsBadRequest {
	return &GETV1UniversesUniverseIDPermissionsBadRequest{}
}

/*GETV1UniversesUniverseIDPermissionsBadRequest handles this case with default header values.

{universeId} is invalid.
*/
type GETV1UniversesUniverseIDPermissionsBadRequest struct {
}

func (o *GETV1UniversesUniverseIDPermissionsBadRequest) Error() string {
	return fmt.Sprintf("[GET /v1/universes/{universeId}/permissions][%d] gETV1UniversesUniverseIdPermissionsBadRequest ", 400)
}

func (o *GETV1UniversesUniverseIDPermissionsBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
