// Code generated by go-swagger; DO NOT EDIT.

package universes

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGETV1UniversesMultigetPermissionsParams creates a new GETV1UniversesMultigetPermissionsParams object
// with the default values initialized.
func NewGETV1UniversesMultigetPermissionsParams() *GETV1UniversesMultigetPermissionsParams {
	var ()
	return &GETV1UniversesMultigetPermissionsParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGETV1UniversesMultigetPermissionsParamsWithTimeout creates a new GETV1UniversesMultigetPermissionsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGETV1UniversesMultigetPermissionsParamsWithTimeout(timeout time.Duration) *GETV1UniversesMultigetPermissionsParams {
	var ()
	return &GETV1UniversesMultigetPermissionsParams{

		timeout: timeout,
	}
}

// NewGETV1UniversesMultigetPermissionsParamsWithContext creates a new GETV1UniversesMultigetPermissionsParams object
// with the default values initialized, and the ability to set a context for a request
func NewGETV1UniversesMultigetPermissionsParamsWithContext(ctx context.Context) *GETV1UniversesMultigetPermissionsParams {
	var ()
	return &GETV1UniversesMultigetPermissionsParams{

		Context: ctx,
	}
}

// NewGETV1UniversesMultigetPermissionsParamsWithHTTPClient creates a new GETV1UniversesMultigetPermissionsParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGETV1UniversesMultigetPermissionsParamsWithHTTPClient(client *http.Client) *GETV1UniversesMultigetPermissionsParams {
	var ()
	return &GETV1UniversesMultigetPermissionsParams{
		HTTPClient: client,
	}
}

/*GETV1UniversesMultigetPermissionsParams contains all the parameters to send to the API endpoint
for the g e t v1 universes multiget permissions operation typically these are written to a http.Request
*/
type GETV1UniversesMultigetPermissionsParams struct {

	/*Ids
	  The universe ids.

	*/
	Ids []int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the g e t v1 universes multiget permissions params
func (o *GETV1UniversesMultigetPermissionsParams) WithTimeout(timeout time.Duration) *GETV1UniversesMultigetPermissionsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the g e t v1 universes multiget permissions params
func (o *GETV1UniversesMultigetPermissionsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the g e t v1 universes multiget permissions params
func (o *GETV1UniversesMultigetPermissionsParams) WithContext(ctx context.Context) *GETV1UniversesMultigetPermissionsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the g e t v1 universes multiget permissions params
func (o *GETV1UniversesMultigetPermissionsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the g e t v1 universes multiget permissions params
func (o *GETV1UniversesMultigetPermissionsParams) WithHTTPClient(client *http.Client) *GETV1UniversesMultigetPermissionsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the g e t v1 universes multiget permissions params
func (o *GETV1UniversesMultigetPermissionsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithIds adds the ids to the g e t v1 universes multiget permissions params
func (o *GETV1UniversesMultigetPermissionsParams) WithIds(ids []int64) *GETV1UniversesMultigetPermissionsParams {
	o.SetIds(ids)
	return o
}

// SetIds adds the ids to the g e t v1 universes multiget permissions params
func (o *GETV1UniversesMultigetPermissionsParams) SetIds(ids []int64) {
	o.Ids = ids
}

// WriteToRequest writes these params to a swagger request
func (o *GETV1UniversesMultigetPermissionsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	var valuesIds []string
	for _, v := range o.Ids {
		valuesIds = append(valuesIds, swag.FormatInt64(v))
	}

	joinedIds := swag.JoinByFormat(valuesIds, "multi")
	// query array param ids
	if err := r.SetQueryParam("ids", joinedIds...); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
