// Code generated by go-swagger; DO NOT EDIT.

package universes

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/janberktold/go-roblox/develop/models"
)

// GETV1UniversesUniverseIDPlacesReader is a Reader for the GETV1UniversesUniverseIDPlaces structure.
type GETV1UniversesUniverseIDPlacesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GETV1UniversesUniverseIDPlacesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGETV1UniversesUniverseIDPlacesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewGETV1UniversesUniverseIDPlacesBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 500:
		result := NewGETV1UniversesUniverseIDPlacesInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGETV1UniversesUniverseIDPlacesOK creates a GETV1UniversesUniverseIDPlacesOK with default headers values
func NewGETV1UniversesUniverseIDPlacesOK() *GETV1UniversesUniverseIDPlacesOK {
	return &GETV1UniversesUniverseIDPlacesOK{}
}

/*GETV1UniversesUniverseIDPlacesOK handles this case with default header values.

GETV1UniversesUniverseIDPlacesOK g e t v1 universes universe Id places o k
*/
type GETV1UniversesUniverseIDPlacesOK struct {
	Payload *models.APIPageResponsePlaceModel
}

func (o *GETV1UniversesUniverseIDPlacesOK) Error() string {
	return fmt.Sprintf("[GET /v1/universes/{universeId}/places][%d] gETV1UniversesUniverseIdPlacesOK  %+v", 200, o.Payload)
}

func (o *GETV1UniversesUniverseIDPlacesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIPageResponsePlaceModel)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGETV1UniversesUniverseIDPlacesBadRequest creates a GETV1UniversesUniverseIDPlacesBadRequest with default headers values
func NewGETV1UniversesUniverseIDPlacesBadRequest() *GETV1UniversesUniverseIDPlacesBadRequest {
	return &GETV1UniversesUniverseIDPlacesBadRequest{}
}

/*GETV1UniversesUniverseIDPlacesBadRequest handles this case with default header values.

Invalid {universeId}.
*/
type GETV1UniversesUniverseIDPlacesBadRequest struct {
}

func (o *GETV1UniversesUniverseIDPlacesBadRequest) Error() string {
	return fmt.Sprintf("[GET /v1/universes/{universeId}/places][%d] gETV1UniversesUniverseIdPlacesBadRequest ", 400)
}

func (o *GETV1UniversesUniverseIDPlacesBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGETV1UniversesUniverseIDPlacesInternalServerError creates a GETV1UniversesUniverseIDPlacesInternalServerError with default headers values
func NewGETV1UniversesUniverseIDPlacesInternalServerError() *GETV1UniversesUniverseIDPlacesInternalServerError {
	return &GETV1UniversesUniverseIDPlacesInternalServerError{}
}

/*GETV1UniversesUniverseIDPlacesInternalServerError handles this case with default header values.

Unknown error retrieving universe information.
*/
type GETV1UniversesUniverseIDPlacesInternalServerError struct {
}

func (o *GETV1UniversesUniverseIDPlacesInternalServerError) Error() string {
	return fmt.Sprintf("[GET /v1/universes/{universeId}/places][%d] gETV1UniversesUniverseIdPlacesInternalServerError ", 500)
}

func (o *GETV1UniversesUniverseIDPlacesInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
