// Code generated by go-swagger; DO NOT EDIT.

package universes

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGETV1UniversesUniverseIDPermissionsParams creates a new GETV1UniversesUniverseIDPermissionsParams object
// with the default values initialized.
func NewGETV1UniversesUniverseIDPermissionsParams() *GETV1UniversesUniverseIDPermissionsParams {
	var ()
	return &GETV1UniversesUniverseIDPermissionsParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGETV1UniversesUniverseIDPermissionsParamsWithTimeout creates a new GETV1UniversesUniverseIDPermissionsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGETV1UniversesUniverseIDPermissionsParamsWithTimeout(timeout time.Duration) *GETV1UniversesUniverseIDPermissionsParams {
	var ()
	return &GETV1UniversesUniverseIDPermissionsParams{

		timeout: timeout,
	}
}

// NewGETV1UniversesUniverseIDPermissionsParamsWithContext creates a new GETV1UniversesUniverseIDPermissionsParams object
// with the default values initialized, and the ability to set a context for a request
func NewGETV1UniversesUniverseIDPermissionsParamsWithContext(ctx context.Context) *GETV1UniversesUniverseIDPermissionsParams {
	var ()
	return &GETV1UniversesUniverseIDPermissionsParams{

		Context: ctx,
	}
}

// NewGETV1UniversesUniverseIDPermissionsParamsWithHTTPClient creates a new GETV1UniversesUniverseIDPermissionsParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGETV1UniversesUniverseIDPermissionsParamsWithHTTPClient(client *http.Client) *GETV1UniversesUniverseIDPermissionsParams {
	var ()
	return &GETV1UniversesUniverseIDPermissionsParams{
		HTTPClient: client,
	}
}

/*GETV1UniversesUniverseIDPermissionsParams contains all the parameters to send to the API endpoint
for the g e t v1 universes universe Id permissions operation typically these are written to a http.Request
*/
type GETV1UniversesUniverseIDPermissionsParams struct {

	/*UniverseID
	  The universe id.

	*/
	UniverseID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the g e t v1 universes universe Id permissions params
func (o *GETV1UniversesUniverseIDPermissionsParams) WithTimeout(timeout time.Duration) *GETV1UniversesUniverseIDPermissionsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the g e t v1 universes universe Id permissions params
func (o *GETV1UniversesUniverseIDPermissionsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the g e t v1 universes universe Id permissions params
func (o *GETV1UniversesUniverseIDPermissionsParams) WithContext(ctx context.Context) *GETV1UniversesUniverseIDPermissionsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the g e t v1 universes universe Id permissions params
func (o *GETV1UniversesUniverseIDPermissionsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the g e t v1 universes universe Id permissions params
func (o *GETV1UniversesUniverseIDPermissionsParams) WithHTTPClient(client *http.Client) *GETV1UniversesUniverseIDPermissionsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the g e t v1 universes universe Id permissions params
func (o *GETV1UniversesUniverseIDPermissionsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithUniverseID adds the universeID to the g e t v1 universes universe Id permissions params
func (o *GETV1UniversesUniverseIDPermissionsParams) WithUniverseID(universeID int64) *GETV1UniversesUniverseIDPermissionsParams {
	o.SetUniverseID(universeID)
	return o
}

// SetUniverseID adds the universeId to the g e t v1 universes universe Id permissions params
func (o *GETV1UniversesUniverseIDPermissionsParams) SetUniverseID(universeID int64) {
	o.UniverseID = universeID
}

// WriteToRequest writes these params to a swagger request
func (o *GETV1UniversesUniverseIDPermissionsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param universeId
	if err := r.SetPathParam("universeId", swag.FormatInt64(o.UniverseID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
