// Code generated by go-swagger; DO NOT EDIT.

package universes

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewPOSTV1UniversesUniverseIDDeactivateParams creates a new POSTV1UniversesUniverseIDDeactivateParams object
// with the default values initialized.
func NewPOSTV1UniversesUniverseIDDeactivateParams() *POSTV1UniversesUniverseIDDeactivateParams {
	var ()
	return &POSTV1UniversesUniverseIDDeactivateParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPOSTV1UniversesUniverseIDDeactivateParamsWithTimeout creates a new POSTV1UniversesUniverseIDDeactivateParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPOSTV1UniversesUniverseIDDeactivateParamsWithTimeout(timeout time.Duration) *POSTV1UniversesUniverseIDDeactivateParams {
	var ()
	return &POSTV1UniversesUniverseIDDeactivateParams{

		timeout: timeout,
	}
}

// NewPOSTV1UniversesUniverseIDDeactivateParamsWithContext creates a new POSTV1UniversesUniverseIDDeactivateParams object
// with the default values initialized, and the ability to set a context for a request
func NewPOSTV1UniversesUniverseIDDeactivateParamsWithContext(ctx context.Context) *POSTV1UniversesUniverseIDDeactivateParams {
	var ()
	return &POSTV1UniversesUniverseIDDeactivateParams{

		Context: ctx,
	}
}

// NewPOSTV1UniversesUniverseIDDeactivateParamsWithHTTPClient creates a new POSTV1UniversesUniverseIDDeactivateParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPOSTV1UniversesUniverseIDDeactivateParamsWithHTTPClient(client *http.Client) *POSTV1UniversesUniverseIDDeactivateParams {
	var ()
	return &POSTV1UniversesUniverseIDDeactivateParams{
		HTTPClient: client,
	}
}

/*POSTV1UniversesUniverseIDDeactivateParams contains all the parameters to send to the API endpoint
for the p o s t v1 universes universe Id deactivate operation typically these are written to a http.Request
*/
type POSTV1UniversesUniverseIDDeactivateParams struct {

	/*UniverseID
	  The universe id.

	*/
	UniverseID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the p o s t v1 universes universe Id deactivate params
func (o *POSTV1UniversesUniverseIDDeactivateParams) WithTimeout(timeout time.Duration) *POSTV1UniversesUniverseIDDeactivateParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the p o s t v1 universes universe Id deactivate params
func (o *POSTV1UniversesUniverseIDDeactivateParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the p o s t v1 universes universe Id deactivate params
func (o *POSTV1UniversesUniverseIDDeactivateParams) WithContext(ctx context.Context) *POSTV1UniversesUniverseIDDeactivateParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the p o s t v1 universes universe Id deactivate params
func (o *POSTV1UniversesUniverseIDDeactivateParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the p o s t v1 universes universe Id deactivate params
func (o *POSTV1UniversesUniverseIDDeactivateParams) WithHTTPClient(client *http.Client) *POSTV1UniversesUniverseIDDeactivateParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the p o s t v1 universes universe Id deactivate params
func (o *POSTV1UniversesUniverseIDDeactivateParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithUniverseID adds the universeID to the p o s t v1 universes universe Id deactivate params
func (o *POSTV1UniversesUniverseIDDeactivateParams) WithUniverseID(universeID int64) *POSTV1UniversesUniverseIDDeactivateParams {
	o.SetUniverseID(universeID)
	return o
}

// SetUniverseID adds the universeId to the p o s t v1 universes universe Id deactivate params
func (o *POSTV1UniversesUniverseIDDeactivateParams) SetUniverseID(universeID int64) {
	o.UniverseID = universeID
}

// WriteToRequest writes these params to a swagger request
func (o *POSTV1UniversesUniverseIDDeactivateParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param universeId
	if err := r.SetPathParam("universeId", swag.FormatInt64(o.UniverseID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
